//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol _SBFakeBlurObserver;

@protocol _SBFakeBlur <NSObject>
@property(nonatomic) unsigned long long transformOptions;
@property(nonatomic, getter=isFullscreen) _Bool fullscreen;
@property(nonatomic) double zoomScale;
@property(nonatomic) __weak id <_SBFakeBlurObserver> observer;
- (void)offsetWallpaperBy:(struct CGPoint)arg1;
- (long long)effectiveStyle;
- (void)requestStyle:(long long)arg1;
@end

