//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class _SBFolderPageElement;

@interface _SBIconGridWrapperView : UIImageView
{
    _SBFolderPageElement *_element;
}

@property(retain, nonatomic) _SBFolderPageElement *element; // @synthesize element=_element;
- (void).cxx_destruct;
- (void)positionAtRow:(unsigned long long)arg1;
- (void)reposition;

@end

