//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_SBIconProgressTransition.h"

@interface _SBIconProgressFractionTransition : _SBIconProgressTransition
{
    double _targetFraction;
}

+ (id)newTransitionToFraction:(double)arg1;
- (_Bool)isCompleteWithView:(id)arg1;
- (void)_updateView:(id)arg1 forDisplayedFraction:(double)arg2;
- (void)completeTransitionAndUpdateView:(id)arg1;
- (void)updateView:(id)arg1 withElapsedTime:(double)arg2;
- (void)updateToFraction:(double)arg1;

@end

