//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _SBMainScreenActiveInterfaceOrientationWindowRootViewController : UIViewController
{
    unsigned long long _supportedInterfaceOrientations;
}

@property(nonatomic) unsigned long long supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
- (id)_viewControllerForSupportedInterfaceOrientationsWithDismissCheck:(_Bool)arg1;
- (_Bool)shouldAutorotate;

@end

