//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class _SBMultiplexedHostView;

@protocol _SBMultiplexedHostViewScreenRectObserver <NSObject>

@optional
- (void)_hostView:(_SBMultiplexedHostView *)arg1 screenRectDidChange:(struct CGRect)arg2;
@end

