//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _SBPowerAssertionContext : NSObject
{
    NSString *_processName;
    CDUnknownBlockType _collectionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType collectionBlock; // @synthesize collectionBlock=_collectionBlock;
@property(copy, nonatomic) NSString *processName; // @synthesize processName=_processName;
- (void).cxx_destruct;

@end

