//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, NSURL;

@protocol AVExternalDeviceDelegate <NSObject>

@optional
- (void)setViewAreaIndex:(long long)arg1 andAdjacentViewAreas:(NSArray *)arg2 forScreenID:(NSString *)arg3;
- (void)siriRequestedWithAction:(long long)arg1;
- (void)iOSUIRequestedForApplicationURL:(NSURL *)arg1;
@end

