//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardUIServices/BSDescriptionBuilder.h>

@interface BSDescriptionBuilder (SBIdleTimerDescriptor)
- (void)sbidletimerdescriptor_appendTimeInterval:(double)arg1 withName:(id)arg2;
@end

