//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class UIScrollView;

@protocol BSUIScrollViewDelegate <UIScrollViewDelegate>

@optional
- (void)scrollViewDidEndScrolling:(UIScrollView *)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1 withContext:(CDStruct_3b09cf25)arg2;
- (void)scrollViewWillBeginScrolling:(UIScrollView *)arg1;
@end

