//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CCUIModularControlCenterViewController;

@protocol CCUIModularControlCenterViewControllerDelegate <NSObject>

@optional
- (void)didCloseExpandedModuleForControlCenterViewController:(CCUIModularControlCenterViewController *)arg1;
- (void)willOpenExpandedModuleForControlCenterViewController:(CCUIModularControlCenterViewController *)arg1;
- (void)controlCenterViewController:(CCUIModularControlCenterViewController *)arg1 didUpdateHomeGestureDismissalAllowed:(_Bool)arg2;
- (void)controlCenterViewControllerDidFinishUserInteractionWithModule:(CCUIModularControlCenterViewController *)arg1;
- (void)controlCenterViewControllerDidBeginUserInteractionWithModule:(CCUIModularControlCenterViewController *)arg1;
@end

