//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DoNotDisturb/DNDEventBehaviorResolutionService.h>

@interface DNDEventBehaviorResolutionService (SpringBoard)
- (void)sb_checkSuppressionForNotificationRequest:(id)arg1 andPerformBlockOnMainThread:(CDUnknownBlockType)arg2;
- (_Bool)sb_shouldSuppressNotificationRequest:(id)arg1;
@end

