//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BSTransactionObserver-Protocol.h"

@class FBApplicationProcess, FBApplicationProcessLaunchTransaction;

@protocol FBApplicationProcessLaunchTransactionObserver <BSTransactionObserver>

@optional
- (void)transaction:(FBApplicationProcessLaunchTransaction *)arg1 didLaunchProcess:(FBApplicationProcess *)arg2;
- (void)transaction:(FBApplicationProcessLaunchTransaction *)arg1 willLaunchProcess:(FBApplicationProcess *)arg2;
@end

