//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardUIServices/FBSApplicationDataStore.h>

@interface FBSApplicationDataStore (SceneStorage)
- (void)_removeAllPersistentSceneData;
- (void)_modifyPersistentSceneData:(unsigned long long)arg1 identifier:(id)arg2 data:(id)arg3;
- (id)_fetchPersistedSceneDataStores;
- (id)_createSceneStoreWithIdentifier:(id)arg1 data:(id)arg2;
- (void)_setCachedSceneDataStores:(id)arg1;
- (id)_cachedSceneDataStores;
- (void)removeAllSceneDataStores;
- (void)removeSceneStoreForIdentifier:(id)arg1;
- (id)sceneStoreForIdentifier:(id)arg1 creatingIfNecessary:(_Bool)arg2;
@end

