//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSDisplayConfiguration, FBSDisplayIdentity, FBSDisplayMonitor;

@protocol FBSDisplayObserving <NSObject>

@optional
- (void)displayMonitor:(FBSDisplayMonitor *)arg1 willDisconnectIdentity:(FBSDisplayIdentity *)arg2;
- (void)displayMonitor:(FBSDisplayMonitor *)arg1 didUpdateIdentity:(FBSDisplayIdentity *)arg2 withConfiguration:(FBSDisplayConfiguration *)arg3;
- (void)displayMonitor:(FBSDisplayMonitor *)arg1 didConnectIdentity:(FBSDisplayIdentity *)arg2 withConfiguration:(FBSDisplayConfiguration *)arg3;
@end

