//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSSceneClientSettings, FBWorkspace, NSString;

@protocol FBWorkspaceDelegate <NSObject>
- (void)workspace:(FBWorkspace *)arg1 didReceiveDestroySceneRequestForIdentifier:(NSString *)arg2 withCompletion:(void (^)(void))arg3;
- (void)workspace:(FBWorkspace *)arg1 didReceiveCreateSceneRequestForIdentifier:(NSString *)arg2 initialClientSettings:(FBSSceneClientSettings *)arg3 withCompletion:(void (^)(FBScene *))arg4;
@end

