//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCNotificationDestination-Protocol.h"

@class NCNotificationRequest;
@protocol NCNotificationAlertDestinationDelegate;

@protocol NCNotificationAlertDestination <NCNotificationDestination>
@property(nonatomic) __weak id <NCNotificationAlertDestinationDelegate> delegate;

@optional
- (void)prepareDestinationToReceiveCriticalNotificationRequest:(NCNotificationRequest *)arg1;
@end

