//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (SBIconIndex)
+ (id)indexPathWithIconIndex:(unsigned long long)arg1 listIndex:(unsigned long long)arg2;
- (id)sb_indexPathByAddingIndexPath:(id)arg1;
- (id)sb_lastIconPathComponent;
- (id)sb_indexPathByRemovingLastIconPathComponent;
- (id)sb_iconRelativePathComponents;
- (unsigned long long)sb_iconPathCount;
- (unsigned long long)sbListIndex;
- (unsigned long long)sbIconIndex;
@end

