//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (PrefsNotifications)
- (id)prefsNotificationsAlertString;
- (id)_alertStringForPref:(id)arg1;
- (id)_callingNamePresentationString:(id)arg1;
- (id)_ssPasswordString:(id)arg1;
- (id)_callingLineIDRestrictionString:(id)arg1;
- (id)_connectedLineIDRestrictionString:(id)arg1;
- (id)_callingLinePresentationString:(id)arg1;
- (id)_connectedLinePresentationString:(id)arg1;
- (id)_fixedDialingString:(id)arg1;
- (id)_callBarringString:(id)arg1;
- (id)_callWaitingString:(id)arg1;
- (id)_callForwardingString:(id)arg1;
- (void)addPrefNotificationWithUserInfo:(id)arg1;
@end

