//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (SBQueueAdditions)
- (id)_sb_peek;
- (id)_sb_dequeue;
- (void)_sb_enqueue:(id)arg1;
@end

