//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface SBActionHandler : NSObject
{
    NSHashTable *_observers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
- (void).cxx_destruct;
- (void)_reportAndKillInsecureProcesses:(id)arg1;
- (void)_executeRestartAction:(id)arg1 fromProcess:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)handleActions:(id)arg1 origin:(id)arg2 withResult:(CDUnknownBlockType)arg3;

@end

