//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RadiosPreferencesDelegate-Protocol.h"

@class RadiosPreferences;
@protocol SBAirplaneModeDelegate;

@interface SBAirplaneModeController : NSObject <RadiosPreferencesDelegate>
{
    RadiosPreferences *_radioPrefs;
    _Bool _cachedInAirplaneMode;
    id <SBAirplaneModeDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <SBAirplaneModeDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)airplaneModeChanged;
@property(nonatomic, getter=isInAirplaneMode) _Bool inAirplaneMode;
- (id)init;

@end

