//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSMutableOrderedSet;

@interface SBAlertItemsObjectQueue : NSObject <NSFastEnumeration>
{
    NSMutableOrderedSet *_objects;
}

@property(retain, nonatomic) NSMutableOrderedSet *objects; // @synthesize objects=_objects;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)objectsOfClass:(Class)arg1;
- (_Bool)hasObjectOfClass:(Class)arg1;
- (void)removeObject:(id)arg1;
- (_Bool)containsObject:(id)arg1;
- (id)dequeueAllObjects;
- (_Bool)hasObject;
- (void)prependObject:(id)arg1;
- (void)appendObject:(id)arg1;
- (id)init;

@end

