//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBAlertItemsSettings : SBUISettings
{
    _Bool _disableBBHandlers;
    long long _testItemToken;
}

+ (id)newTestItemForToken:(long long)arg1;
+ (id)settingsControllerModule;
@property(nonatomic) long long testItemToken; // @synthesize testItemToken=_testItemToken;
@property(nonatomic) _Bool disableBBHandlers; // @synthesize disableBBHandlers=_disableBBHandlers;
- (void)setDefaultValues;

@end

