//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBAlertItem;
@protocol SBAlertItemPresenter;

@interface SBAlertItemPresentation : NSObject
{
    SBAlertItem *_alertItem;
    id <SBAlertItemPresenter> _presenter;
}

@property(retain, nonatomic) id <SBAlertItemPresenter> presenter; // @synthesize presenter=_presenter;
@property(retain, nonatomic) SBAlertItem *alertItem; // @synthesize alertItem=_alertItem;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithAlertItem:(id)arg1 presenter:(id)arg2;

@end

