//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAlertWindow;

@protocol SBAlertWindowDelegate <NSObject>
- (unsigned long long)defaultSupportedInterfaceOrientationsForAlertWindow:(SBAlertWindow *)arg1;
- (long long)defaultInterfaceOrientationForPresentationOfAlertWindow:(SBAlertWindow *)arg1;
- (_Bool)defaultShouldAutorotateForAlertWindow:(SBAlertWindow *)arg1;
@end

