//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAlertWindowViewController;

@protocol SBAlertWindowViewControllerDelegate <NSObject>
- (long long)activeInterfaceOrientationForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (unsigned long long)defaultSupportedInterfaceOrientationsForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (long long)defaultInterfaceOrientationForPresentationOfAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (_Bool)defaultShouldAutorotateForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
@end

