//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBAnalyticsBackend;

@interface SBAnalyticsClient : NSObject
{
    SBAnalyticsBackend *_backend;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_noteSignificantTimeChanged:(id)arg1;
- (void)registerForQueryName:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;
- (void)emitEvent:(unsigned long long)arg1 withPayload:(id)arg2;
- (void)emitEvent:(unsigned long long)arg1;
- (id)initWithBackend:(id)arg1;

@end

