//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAppViewController;

@protocol SBAppViewControllerDelegate <NSObject>

@optional
- (_Bool)appViewControllerShouldBackgroundApplicationOnDeactivate:(SBAppViewController *)arg1;
- (void)appViewControllerDidBecomeReady:(SBAppViewController *)arg1;
- (void)appViewControllerDidDeactivateApplication:(SBAppViewController *)arg1;
- (void)appViewControllerWillActivateApplication:(SBAppViewController *)arg1;
- (void)appViewController:(SBAppViewController *)arg1 didTransitionFromMode:(long long)arg2 toMode:(long long)arg3;
- (_Bool)appViewController:(SBAppViewController *)arg1 shouldTransitionToMode:(long long)arg2;
@end

