//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SBAppSwitcherSnapshotLockoutViewControllerProvider : NSObject
{
    NSMutableArray *_availableControllers;
}

- (void).cxx_destruct;
- (void)_receivedMemoryWarning:(id)arg1;
- (void)recycleLockoutViewController:(id)arg1;
- (id)lockoutViewControllerForBundleIdentifier:(id)arg1;
- (void)dealloc;
- (id)init;

@end

