//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBAppIconForceTouchSettings : SBUISettings
{
    _Bool _enableUIPreviewInteractionAnimations;
    float _animationDurationMultiplier;
}

+ (id)settingsControllerModule;
+ (id)defaults;
@property(nonatomic) _Bool enableUIPreviewInteractionAnimations; // @synthesize enableUIPreviewInteractionAnimations=_enableUIPreviewInteractionAnimations;
@property(nonatomic) float animationDurationMultiplier; // @synthesize animationDurationMultiplier=_animationDurationMultiplier;
- (void)setDefaultValues;

@end

