//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@class SBApplication;

@interface SBApplicationLaunchNotifyAlertItem : SBAlertItem
{
    SBApplication *_application;
}

@property(readonly, nonatomic) SBApplication *application; // @synthesize application=_application;
- (void).cxx_destruct;
- (_Bool)dismissOnLock;
- (id)initWithApplication:(id)arg1;

@end

