//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBAppSwitcherRemoteAlertSet;

@interface SBAppSwitcherRemoteAlertManager : NSObject
{
    SBAppSwitcherRemoteAlertSet *_remoteAlerts;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)currentRemoteAlerts;
- (void)removeRemoteAlert:(id)arg1;
- (void)addRemoteAlert:(id)arg1;

@end

