//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBSceneView.h>

@class SBApplication, SBApplicationSceneHandle;

@interface SBApplicationSceneView : SBSceneView
{
}

@property(readonly, nonatomic) SBApplication *application;
- (id)initWithSceneHandle:(id)arg1 referenceSize:(struct CGSize)arg2 orientation:(long long)arg3 hostRequester:(id)arg4;
- (id)deviceApplicationSceneView;

// Remaining properties
@property(readonly, nonatomic) SBApplicationSceneHandle *sceneHandle; // @dynamic sceneHandle;

@end

