//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "_UISettingsKeyObserver-Protocol.h"

@class NSString, SBAppSwitcherSettings;

@interface SBAppSwitcherSoftOutlineShadowView : UIView <_UISettingsKeyObserver>
{
    SBAppSwitcherSettings *_settings;
    _Bool _isHighlighted;
    _Bool _shouldClip;
    struct CGRect _clippingFrame;
}

@property(nonatomic) struct CGRect clippingFrame; // @synthesize clippingFrame=_clippingFrame;
@property(nonatomic) _Bool shouldClip; // @synthesize shouldClip=_shouldClip;
- (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)_updateShadowParameters;
- (void)_applyPrototypeSettingsToConstants;
@property(nonatomic, getter=isHighlighted) _Bool highlighted;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

