//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface SBAppSwitcherServiceSet : NSObject <NSCopying>
{
    NSMutableArray *_services;
}

@property(readonly, nonatomic) NSMutableArray *services; // @synthesize services=_services;
- (void).cxx_destruct;
- (id)appLayouts;
- (id)serviceBundleIdentifiers;
- (id)serviceForBundleIdentifier:(id)arg1;
- (id)serviceAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)removeService:(id)arg1;
- (void)addService:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithServices:(id)arg1 zone:(struct _NSZone *)arg2;

@end

