//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoard/FBApplicationPlaceholder.h>

@class NSString;

@interface SBApplicationPlaceholderProxy : FBApplicationPlaceholder
{
    NSString *_customIconClassName;
}

@property(copy) NSString *customIconClassName; // @synthesize customIconClassName=_customIconClassName;
- (void).cxx_destruct;
@property(readonly, nonatomic) Class iconClass;
- (void)_reloadFromProxy:(id)arg1;

@end

