//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBApplicationBlurSnapshotGenerationContainerView : UIView
{
    UIView *_wallpaperView;
    UIView *_realSnapshotView;
    UIView *_liveBlurView;
}

@property(retain, nonatomic) UIView *liveBlurView; // @synthesize liveBlurView=_liveBlurView;
@property(retain, nonatomic) UIView *realSnapshotView; // @synthesize realSnapshotView=_realSnapshotView;
@property(retain, nonatomic) UIView *wallpaperView; // @synthesize wallpaperView=_wallpaperView;
- (void).cxx_destruct;
- (void)layoutSubviews;

@end

