//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface SBAppSwitcherRemoteAlertSet : NSObject <NSCopying>
{
    NSMutableArray *_alerts;
}

- (void).cxx_destruct;
- (id)appLayouts;
- (id)serviceBundleIdentifiers;
- (id)alertForAppLayout:(id)arg1;
- (id)alertForBundleIdentifier:(id)arg1;
- (id)alertAtIndex:(unsigned long long)arg1;
- (_Bool)containsAlert:(id)arg1;
- (id)allAlerts;
- (unsigned long long)count;
- (void)removeRemoteAlert:(id)arg1;
- (void)addRemoteAlert:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAlertSet:(id)arg1 zone:(struct _NSZone *)arg2;

@end

