//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAppLayout, SBMainWorkspaceTransitionRequest;

@protocol SBAppSwitcherPageContentView <NSObject>
@property(readonly, nonatomic) _Bool contentRequiresGroupOpacity;
@property(nonatomic) long long orientation;
@property(nonatomic) double cornerRadius;
- (void)setVisible:(_Bool)arg1;
- (void)setActive:(_Bool)arg1;
- (void)invalidate;

@optional
- (void)transitionDidEnd:(_Bool)arg1 forPresentation:(_Bool)arg2 transitionRequest:(SBMainWorkspaceTransitionRequest *)arg3;
- (void)viewDismissing:(SBAppLayout *)arg1 forTransitionRequest:(SBMainWorkspaceTransitionRequest *)arg2;
- (void)viewPresenting:(SBAppLayout *)arg1 forTransitionRequest:(SBMainWorkspaceTransitionRequest *)arg2;
- (void)setShowingIconOverlayView:(_Bool)arg1;
- (void)setShouldUseBrightMaterial:(_Bool)arg1;
@end

