//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UABestAppSuggestionManagerDelegate-Protocol.h"

@class NSCountedSet, NSString, SBBestAppSuggestion, UABestAppSuggestion, UABestAppSuggestionManager, _DECConsumer, _DECResult;

@interface SBAppSuggestionManager : NSObject <UABestAppSuggestionManagerDelegate>
{
    UABestAppSuggestionManager *_continuitySuggestionManager;
    UABestAppSuggestion *_continuityCurrentBestSuggestion;
    _DECConsumer *_expertCenterSuggestionMonitor;
    _DECResult *_currentExpertBestSuggestion;
    SBBestAppSuggestion *_currentBestSuggestion;
    NSCountedSet *_listeningReasons;
    _Bool _isListeningForContinuitySuggestion;
    _Bool _isListeningForExpertCenterSuggestion;
    _Bool _screenOnDueToUserEvent;
    _Bool _screenOnAndLookingForEvent;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (unsigned long long)_supportedExpertCenterCategories;
- (void)expertCenterSuggestionChanged:(id)arg1;
- (void)_handleAppUninstall:(id)arg1;
- (void)bestAppSuggestionChanged:(id)arg1;
- (void)_calculateBestSuggestionAndNotifyListeners;
- (void)noteNotActivatingForAppSuggestion:(id)arg1 fromSource:(long long)arg2;
- (void)noteActivatingForAppSuggestion:(id)arg1 fromSource:(long long)arg2;
- (void)_setContinuitySuggestionUpdatesEnabled:(_Bool)arg1 expertCenterSuggestionUpdatesEnabled:(_Bool)arg2;
- (void)_evaluateSuggestionUpdates:(id)arg1;
- (void)_handleInitialSpringBoardLaunch;
- (void)_nextUserEventOccured:(id)arg1;
- (void)_screenDidUndim:(id)arg1;
- (void)_screenDidDim:(id)arg1;
- (void)disableListeningForUpdatesForReason:(id)arg1;
- (void)enableListeningForUpdatesForReason:(id)arg1;
- (void)startFetchingPayloadForAppSuggestion:(id)arg1;
- (void)performWithCurrentSuggestedAppAndApplication:(CDUnknownBlockType)arg1;
- (id)currentSuggestedApp;
- (void)_stopListeningForNotifications;
- (void)_listenForNotifications;
- (void)_destroySuggestionSources;
- (void)_createSuggestionSources;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

