//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWindow.h"

@class SBAssistantRootViewController;

@interface SBAssistantWindow : SBWindow
{
}

+ (_Bool)_isSecure;
+ (_Bool)sb_autorotates;
+ (id)defaultLayoutStrategy;
- (_Bool)_canBecomeKeyWindow;
- (_Bool)isOpaque;
@property(readonly, nonatomic) SBAssistantRootViewController *assistantRootViewController; // @dynamic assistantRootViewController;
- (void)dealloc;
- (id)initWithScreen:(id)arg1 layoutStrategy:(id)arg2 debugName:(id)arg3 scene:(id)arg4;

@end

