//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAssistantController;

@protocol SBAssistantObserver <NSObject>

@optional
- (void)assistant:(SBAssistantController *)arg1 viewDidDisappear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewWillDisappear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewDidAppear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewWillAppear:(long long)arg2;
@end

