//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAttentionAwarenessClient;

@protocol SBAttentionAwarenessClientDelegate <NSObject>
- (void)clientDidResetForUserAttention:(SBAttentionAwarenessClient *)arg1;
- (void)client:(SBAttentionAwarenessClient *)arg1 attentionLostTimeoutDidExpire:(double)arg2 forConfigurationGeneration:(unsigned long long)arg3 withAssociatedObject:(id)arg4;
@end

