//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBAttentionAwareIdleTimerTimeoutContext : NSObject
{
    long long _expectation;
}

@property(readonly, nonatomic) long long expectation; // @synthesize expectation=_expectation;
- (id)description;
- (id)initWithExpectation:(long long)arg1;

@end

