//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAWDMetric.h"

@class AWDServerConnection;

@interface SBAWDQueryableMetric : SBAWDMetric
{
    AWDServerConnection *_connection;
    CDUnknownBlockType _builder;
}

- (void).cxx_destruct;
- (void)_postQueryableMetric;
- (void)registerWithDataBuilder:(CDUnknownBlockType)arg1;

@end

