//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBBannerContainerViewController;

@protocol SBBannerContainerViewControllerDelegate
- (void)bannerViewControllerDidDismissAction:(SBBannerContainerViewController *)arg1;
- (void)bannerViewControllerDidSelectAction:(SBBannerContainerViewController *)arg1;
@end

