//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SBHomeGestureParticipantDelegate-Protocol.h"

@class SBBarSwipeAffordanceView, SBHomeGestureParticipant;

@interface SBBarSwipeAffordanceViewController : UIViewController <SBHomeGestureParticipantDelegate>
{
    long long _homeGestureParticipantIdentifier;
    SBHomeGestureParticipant *_homeGestureParticipant;
    _Bool _wantsToBeActiveAffordance;
    _Bool _suppressAffordance;
}

@property(nonatomic) _Bool suppressAffordance; // @synthesize suppressAffordance=_suppressAffordance;
@property(nonatomic) _Bool wantsToBeActiveAffordance; // @synthesize wantsToBeActiveAffordance=_wantsToBeActiveAffordance;
- (void).cxx_destruct;
- (void)_updateActiveState;
- (void)_stopTryingToBecomeActiveAffordance;
- (void)_beginTryingToBecomeActiveAffordance;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (void)loadView;
- (id)initWithHomeGestureParticipantIdentifier:(long long)arg1;

// Remaining properties
@property(retain, nonatomic) SBBarSwipeAffordanceView *view; // @dynamic view;

@end

