//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBHomeGesturePanGestureRecognizer.h"

@protocol SBBarSwipeScreenEdgePanGestureRecognizerDelegate;

@interface SBBarSwipeScreenEdgePanGestureRecognizer : SBHomeGesturePanGestureRecognizer
{
    id <SBBarSwipeScreenEdgePanGestureRecognizerDelegate> _interfaceDelegate;
}

@property(nonatomic) __weak id <SBBarSwipeScreenEdgePanGestureRecognizerDelegate> interfaceDelegate; // @synthesize interfaceDelegate=_interfaceDelegate;
- (void).cxx_destruct;
- (long long)_touchInterfaceOrientation;

@end

