//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBBacklightController;

@protocol SBBacklightControllerObserver <NSObject>

@optional
- (void)backlightController:(SBBacklightController *)arg1 didAnimateBacklightToFactor:(float)arg2 source:(long long)arg3;
- (void)backlightController:(SBBacklightController *)arg1 willAnimateBacklightToFactor:(float)arg2 source:(long long)arg3;
@end

