//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBBannerViewCallbackManager, SBUIBannerContext;
@protocol SBUIBannerView;

@interface SBBannerContextView : UIView
{
    SBBannerViewCallbackManager *_callbacks;
    SBBannerViewCallbackManager *_wrapperCallbacks;
    SBUIBannerContext *_bannerContext;
    UIView<SBUIBannerView> *_bannerView;
}

@property(readonly, retain, nonatomic) UIView<SBUIBannerView> *bannerView; // @synthesize bannerView=_bannerView;
@property(readonly, nonatomic) SBUIBannerContext *bannerContext; // @synthesize bannerContext=_bannerContext;
- (void).cxx_destruct;
- (void)noteDidDismissWithReason:(int)arg1;
- (void)noteWillDismissWithReason:(int)arg1;
- (void)noteDidAppear;
- (void)noteWillAppear;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setBannerContext:(id)arg1 withReplaceReason:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

