//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BSDescriptionProviding-Protocol.h"

@protocol SBBiometricUnlockBehaviorDelegate;

@protocol SBBiometricUnlockBehavior <BSDescriptionProviding>
@property(nonatomic) __weak id <SBBiometricUnlockBehaviorDelegate> biometricUnlockBehaviorDelegate;
- (void)handleBiometricEvent:(unsigned long long)arg1;
@end

