//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBBiometricMonitorView : UIView
{
    UIView *_stateView;
    UIView *_presenceView;
    UIView *_poseView;
    long long _matchState;
    long long _presenceDetectState;
    long long _poseState;
}

@property(nonatomic) long long poseState; // @synthesize poseState=_poseState;
@property(nonatomic) long long presenceDetectState; // @synthesize presenceDetectState=_presenceDetectState;
@property(nonatomic) long long matchState; // @synthesize matchState=_matchState;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

