//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBUIBiometricResourceObserver-Protocol.h"

@class BiometricKit, NSString;
@protocol SBUIBiometricResource, SBUILockStateProvider;

@interface SBBiometricEventLogger : NSObject <SBUIBiometricResourceObserver>
{
    BiometricKit *_biometricKit;
    _Bool _isScreenOn;
    _Bool _passcodeSuccessAfterBioFailureTriggerArmed;
    id <SBUIBiometricResource> _biometricResource;
    _Bool _fingerOnWithScreenOn;
    unsigned long long _fingerOnTime;
    unsigned long long _keybagUnlockTime;
    id <SBUILockStateProvider> _uiLockStateProvider;
}

+ (void)logClass:(unsigned char)arg1 code:(unsigned int)arg2;
+ (void)logEvent:(unsigned int)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic, setter=setUILockStateProvider:) id <SBUILockStateProvider> uiLockStateProvider; // @synthesize uiLockStateProvider=_uiLockStateProvider;
@property(nonatomic) unsigned long long keybagUnlockTime; // @synthesize keybagUnlockTime=_keybagUnlockTime;
@property(nonatomic) _Bool fingerOnWithScreenOn; // @synthesize fingerOnWithScreenOn=_fingerOnWithScreenOn;
@property(nonatomic) unsigned long long fingerOnTime; // @synthesize fingerOnTime=_fingerOnTime;
- (void).cxx_destruct;
- (unsigned long long)_machTimeInMilliseconds;
- (void)timestampEvent:(unsigned long long)arg1;
- (_Bool)_shouldSyslogTimestamps;
- (void)_resetPasscodeStateMachine;
- (void)_biometricAuthenticationFailed;
- (void)_biometricAuthenticationSucceeded;
- (void)_passcodeAuthenticationSucceeded;
- (void)biometricResource:(id)arg1 observeEvent:(unsigned long long)arg2;
- (void)_deviceOrientationDidChange:(id)arg1;
- (void)_proudLockIconViewWouldStartScanningOnFaceInView:(id)arg1;
- (void)_proudLockIconViewWouldStartScanningOnMatchStart:(id)arg1;
- (void)_proudLockIconViewCausedDelayedUnlock:(id)arg1;
- (void)_proudLockIconViewStateDidChange:(id)arg1;
- (void)_unlockRequested:(id)arg1;
- (void)_passcodeViewTransitionedToPasscode:(id)arg1;
- (void)_coversheetSwipedForDismissal:(id)arg1;
- (void)_passcodePromptCancelled:(id)arg1;
- (void)_systemDidWakeFromSleep:(id)arg1;
- (void)_authRequestCompleted:(id)arg1;
- (void)_prearmMatch:(id)arg1;
- (void)_unlockAnimationWillStart:(id)arg1;
- (void)_keybagBioUnlock:(id)arg1;
- (void)_tryAgain:(id)arg1;
- (void)_fingerOn:(id)arg1;
- (void)_backlightLevelChanged:(id)arg1;
- (void)_screenTurnedOn:(id)arg1;
- (void)_clearEverything;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

