//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface SBBluetoothAccessoryBatteryMonitor : NSObject
{
    NSMutableSet *_accessoryNamesInLowPower;
}

- (void).cxx_destruct;
- (id)descriptionBuilder;
- (id)description;
- (void)dealloc;
- (void)_popLowPowerAlertForAccessoryIfNecessary:(id)arg1;
- (id)init;

@end

