//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, UISystemNavigationAction;

@interface SBBreadcrumbActionContext : NSObject
{
    UISystemNavigationAction *_action;
    NSDictionary *_destinationContexts;
    CDUnknownBlockType _responseHandler;
}

@property(copy, nonatomic) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property(copy, nonatomic) NSDictionary *destinationContexts; // @synthesize destinationContexts=_destinationContexts;
@property(retain, nonatomic) UISystemNavigationAction *action; // @synthesize action=_action;
- (void).cxx_destruct;

@end

