//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BBSystemStateProvider;

@interface SBBulletinSystemStateAdapter : NSObject
{
    BBSystemStateProvider *_stateProvider;
    _Bool _quietModeEnabled;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_lostModeStateChanged;
- (void)_lockStateChanged:(id)arg1;
- (void)_sendCurrentUILockedStatus;
- (void)dealloc;
- (id)init;

@end

