//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBApplicationSceneEntity.h"

@interface SBCarApplicationSceneEntity : SBApplicationSceneEntity
{
}

- (_Bool)_isValidCarActivationSetting:(unsigned int)arg1;
- (id)carApplicationSceneEntity;
- (_Bool)isCarApplicationSceneEntity;
- (void)applyActivationSettings:(id)arg1;
- (void)setObject:(id)arg1 forActivationSetting:(unsigned int)arg2;
- (void)setFlag:(long long)arg1 forActivationSetting:(unsigned int)arg2;
- (Class)viewControllerClass;
- (id)initWithApplicationSceneEntity:(id)arg1 screenController:(id)arg2;
- (id)initWithApplication:(id)arg1 screenController:(id)arg2;
- (id)initWithApplicationSceneHandle:(id)arg1;

@end

