//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBCarPlayIconImageCache : NSObject
{
}

+ (id)_imageKeyForBundleIdentifier:(id)arg1 inLayout:(id)arg2;
+ (id)_iconImageCache;
+ (id)sharedInstance;
- (void)setIconImage:(id)arg1 forBundleIdentifier:(id)arg2 inLayout:(id)arg3;
- (id)iconImageForBundleIdentifier:(id)arg1 inLayout:(id)arg2;

@end

