//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconModelPropertyListFileStore.h"

@class NSString;

@interface SBCarPlayIconModelStore : SBIconModelPropertyListFileStore
{
    NSString *_vehicleId;
}

@property(readonly, nonatomic) NSString *vehicleId; // @synthesize vehicleId=_vehicleId;
- (void).cxx_destruct;
- (id)initWithVehicleId:(id)arg1;

@end

