//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBCarDisplaySettings : SBUISettings
{
    _Bool _animateLockOutModeChanges;
    long long _lockOutMode;
    long long _pairingOverride;
    long long _wirelessOverride;
}

+ (id)settingsControllerModule;
@property long long wirelessOverride; // @synthesize wirelessOverride=_wirelessOverride;
@property long long pairingOverride; // @synthesize pairingOverride=_pairingOverride;
@property long long lockOutMode; // @synthesize lockOutMode=_lockOutMode;
@property _Bool animateLockOutModeChanges; // @synthesize animateLockOutModeChanges=_animateLockOutModeChanges;
- (void)setDefaultValues;

@end

