//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBChestnutController : NSObject
{
    unsigned long long _effectiveChestnutValue;
    unsigned long long _fileState;
    unsigned long long _requestState;
    unsigned long long _retryAttemptNumber;
}

- (void)_startNetworkRequestAfterDelay:(double)arg1;
- (void)_attemptFetchChestnutIfAppropriate;
- (unsigned long long)_chestnutValueFromDictionary:(id)arg1;
- (unsigned long long)_attemptReadingFromDisk;
@property(readonly, nonatomic) unsigned long long chestnutKey1Value;
- (id)init;

@end

