//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBHomeScreenButton.h"

@class UITapGestureRecognizer;
@protocol SBCloseBoxViewDelegate;

@interface SBCloseBoxView : SBHomeScreenButton
{
    UITapGestureRecognizer *_actionTapGestureRecognizer;
    id <SBCloseBoxViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SBCloseBoxViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITapGestureRecognizer *actionTapGestureRecognizer; // @synthesize actionTapGestureRecognizer=_actionTapGestureRecognizer;
- (void).cxx_destruct;
- (_Bool)shouldTrack;

@end

