//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAWDMetric.h"

@interface SBClawGestureMetric : SBAWDMetric
{
}

- (id)configureWithData:(id)arg1;
- (Class)dataClass;
- (unsigned long long)metricID;
- (void)postWithDataBuilder:(CDUnknownBlockType)arg1;

@end

