//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBToAppsWorkspaceTransaction.h"

@class BSTransaction, SBAlertToAppsWorkspaceTransaction, SBDismissOverlaysAnimationController;

@interface SBCoverSheetToAppsWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    BSTransaction *_carPlayTransaction;
    SBAlertToAppsWorkspaceTransaction *_alertToAppsTransaction;
    SBDismissOverlaysAnimationController *_dismissOverlaysAnimationController;
    _Bool _preservesBanners;
}

@property(nonatomic) _Bool preservesBanners; // @synthesize preservesBanners=_preservesBanners;
@property(retain, nonatomic) BSTransaction *carPlayTransaction; // @synthesize carPlayTransaction=_carPlayTransaction;
- (void).cxx_destruct;
- (unsigned long long)_dismissOverlaysOptions;
- (void)_dismissOverlaysIfNeeded;
- (void)_coverSheetDidDismiss:(id)arg1;
- (void)activateApplications;
- (void)_begin;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

@end

