//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDisplayItem.h"

@class SBBestAppSuggestion;

@interface SBContinuityDisplayItem : SBDisplayItem
{
    SBBestAppSuggestion *_appSuggestion;
}

@property(readonly, nonatomic) SBBestAppSuggestion *appSuggestion; // @synthesize appSuggestion=_appSuggestion;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithType:(struct NSString *)arg1 displayIdentifier:(id)arg2 appSuggestion:(id)arg3;
- (id)initWithType:(id)arg1 displayIdentifier:(id)arg2;

@end

