//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CCUIControlCenterSystemAgent-Protocol.h"

@class NSString;

@interface SBControlCenterSystemAgent : NSObject <CCUIControlCenterSystemAgent>
{
}

- (id)hideStatusBarAssertion;
- (_Bool)isUILocked;
- (id)frontmostApplicationDisplayID;
- (id)getFGSceneIdentifiers;
- (_Bool)wifiIsPowered;
- (_Bool)wifiDevicePresent;
- (void)setWifiPowered:(_Bool)arg1;
- (void)updateWifiDevicePresence;
- (_Bool)isInAirplaneMode;
- (_Bool)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (_Bool)wirelessDisplayRouteIsPicked;
- (id)nameOfPickedRoute;
- (_Bool)handsetRouteIsSelected;
- (void)setRingerMuted:(_Bool)arg1;
- (_Bool)isRingerMuted;
- (void)promptForUnlockIfNecessary:(CDUnknownBlockType)arg1;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2 unlockIfNecessary:(_Bool)arg3;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)prototypeSettings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

