//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewBase.h"

@class SBDashBoardHomeAffordanceView, UIView;

@interface SBCoverSheetSecureAppEnvironmentView : SBDashBoardViewBase
{
    UIView *_homeAffordanceContainerView;
    SBDashBoardHomeAffordanceView *_homeAffordanceView;
}

@property(retain, nonatomic) SBDashBoardHomeAffordanceView *homeAffordanceView; // @synthesize homeAffordanceView=_homeAffordanceView;
@property(retain, nonatomic) UIView *homeAffordanceContainerView; // @synthesize homeAffordanceContainerView=_homeAffordanceContainerView;
- (void).cxx_destruct;
- (void)_layoutHomeAffordanceContainer;
- (void)layoutSubviews;

@end

