//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, SBDashBoardNotificationAdjunctListViewController;

@protocol SBDashBoardNotificationAdjunctListViewControllerDelegate
- (void)adjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1 didUpdateWithSize:(struct CGSize)arg2;
- (double)interItemSpacingToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
- (struct UIEdgeInsets)insetMarginsToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
- (struct CGSize)sizeToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
- (NSString *)groupNameForRecipe:(long long)arg1 adjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg2;
@end

