//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SBDashBoardLockProviding <NSObject>
@property(readonly, nonatomic) _Bool showPasscode;
@property(readonly, nonatomic, getter=isLocked) _Bool locked;
- (_Bool)unlockFromSource:(int)arg1;
@end

