//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBLockScreenEmergencyDialerDelegate-Protocol.h"

@class NSString, SBLockScreenEmergencyDialerController, TUCallCenter;

@interface SBDashBoardEmergencyDialerViewController : SBDashBoardViewControllerBase <SBLockScreenEmergencyDialerDelegate>
{
    TUCallCenter *_callCenter;
    SBLockScreenEmergencyDialerController *_controller;
    _Bool _inEmergencyCall;
    _Bool _inEmergencyCallMode;
}

- (void).cxx_destruct;
- (void)_updateEmergencyCallMode:(id)arg1;
- (void)_deactivateEmergencyDialerController;
- (void)_activateEmergencyDialerController;
- (void)emergencyDialer:(id)arg1 willDeactivateWithError:(id)arg2;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

