//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUIServices/SBUIVibrantButton.h>

@class SBWallpaperEffectView;

@interface SBDashBoardVibrantWallpaperButton : SBUIVibrantButton
{
    SBWallpaperEffectView *_effectView;
}

@property(readonly, nonatomic) SBWallpaperEffectView *effectView; // @synthesize effectView=_effectView;
- (void).cxx_destruct;
- (void)_updateVibrancy;
- (void)setLegibilitySettings:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

