//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDashBoardAdjunctListModel;
@protocol SBDashBoardAdjunctListItemProviding;

@protocol SBDashBoardAdjunctListModelDelegate <NSObject>
- (void)adjunctListModel:(SBDashBoardAdjunctListModel *)arg1 didRemoveItem:(id <SBDashBoardAdjunctListItemProviding>)arg2;
- (void)adjunctListModel:(SBDashBoardAdjunctListModel *)arg1 didAddItem:(id <SBDashBoardAdjunctListItemProviding>)arg2;
@end

