//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDataPlanAccountAlertItem.h"

@class NSNumber;

@interface SBDataPlanUsageAlertItem : SBDataPlanAccountAlertItem
{
    NSNumber *_remainingPortion;
}

@property(retain, nonatomic) NSNumber *remainingPortion; // @synthesize remainingPortion=_remainingPortion;
- (void).cxx_destruct;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (id)initWithAccountURL:(id)arg1 usage:(id)arg2;

@end

