//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDashBoardEventHandling-Protocol.h"

@class NSString, SBDashBoardUserPictureView, UMUser;

@interface SBDashBoardUserPictureViewController : SBDashBoardViewControllerBase <SBDashBoardEventHandling>
{
    UMUser *_user;
    SBDashBoardUserPictureView *_userPictureView;
}

+ (Class)viewClass;
+ (_Bool)isUserPictureSupported;
- (void).cxx_destruct;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationType;
- (long long)presentationStyle;
- (long long)presentationPriority;
- (void)aggregateAppearance:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (id)view;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

