//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIColor, UIVisualEffect, UIVisualEffectView;

@interface SBDashBoardModalButton : UIButton
{
    UIColor *_backgroundColor;
    UIVisualEffectView *_effectView;
    _Bool _isPressed;
}

- (void).cxx_destruct;
- (void)_buttonReleased:(id)arg1;
- (void)_buttonPressed:(id)arg1;
- (void)layoutSubviews;
- (void)_setContinuousCornerRadius:(double)arg1;
- (void)setBackgroundColor:(id)arg1;
- (id)backgroundColor;
@property(retain, nonatomic) UIVisualEffect *visualEffect;
- (id)initWithFrame:(struct CGRect)arg1;

@end

