//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBLockScreenNowPlayingController.h"

@class SBDashBoardMediaControlsViewController;

@interface SBDashBoardNowPlayingController : SBLockScreenNowPlayingController
{
    SBDashBoardMediaControlsViewController *_controlsViewController;
}

@property(readonly, nonatomic) SBDashBoardMediaControlsViewController *controlsViewController; // @synthesize controlsViewController=_controlsViewController;
- (void).cxx_destruct;
- (id)initWithMediaController:(id)arg1;

@end

