//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBDaemonRequest : NSObject
{
    CDUnknownBlockType _enabler;
    CDUnknownBlockType _disabler;
}

+ (id)requestWithEnabler:(CDUnknownBlockType)arg1 disabler:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) CDUnknownBlockType disabler; // @synthesize disabler=_disabler;
@property(copy, nonatomic) CDUnknownBlockType enabler; // @synthesize enabler=_enabler;
- (void).cxx_destruct;
- (void)dispatchDisablerOnQueue:(id)arg1;
- (void)dispatchEnablerOnQueue:(id)arg1;

@end

