//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class SBDashBoardTodayViewController, UINavigationController;

@interface SBDashBoardTodayContentViewController : SBDashBoardViewControllerBase
{
    _Bool _bouncing;
    SBDashBoardTodayViewController *_todayViewController;
    UINavigationController *_spotlightNavigationController;
}

+ (Class)viewClass;
@property(retain, nonatomic) UINavigationController *spotlightNavigationController; // @synthesize spotlightNavigationController=_spotlightNavigationController;
@property(nonatomic, getter=isBouncing) _Bool bouncing; // @synthesize bouncing=_bouncing;
@property(retain, nonatomic) SBDashBoardTodayViewController *todayViewController; // @synthesize todayViewController=_todayViewController;
- (void).cxx_destruct;
- (id)_todayContentView;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

