//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBDaemonHandler : NSObject
{
}

+ (void)noteDaemonCanceled:(id)arg1;
+ (id)stateDescription;
+ (void)removeRequestForKey:(id)arg1 forDaemonPid:(int)arg2;
+ (_Bool)addRequest:(id)arg1 forKey:(id)arg2 forDaemonPid:(int)arg3;
+ (void)initialize;

@end

