//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardParticipating-Protocol.h"

@protocol SBDashBoardViewTransitionSource <SBDashBoardParticipating>
@property(readonly, nonatomic) CDStruct_7238a68f transitionContext;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
- (void)cancelTransition;
@end

