//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardAppearanceProviding-Protocol.h"
#import "SBDashBoardBehaviorProviding-Protocol.h"
#import "SBDashBoardEventHandling-Protocol.h"
#import "SBDashBoardParticipating-Protocol.h"
#import "SBDashBoardPresentationProviding-Protocol.h"

@protocol SBDashBoardViewPresenting;

@protocol SBDashBoardViewControlling <SBDashBoardAppearanceProviding, SBDashBoardBehaviorProviding, SBDashBoardPresentationProviding, SBDashBoardEventHandling, SBDashBoardParticipating>
@property(readonly, nonatomic) long long presentationAltitude;
@property(readonly, nonatomic) long long presentationPriority;
@property(readonly, nonatomic) long long presentationTransition;
@property(readonly, nonatomic) long long presentationType;
@property(readonly, nonatomic) long long presentationStyle;
@property(nonatomic) __weak id <SBDashBoardViewPresenting> presenter;
@end

