//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBApplicationHosting-Protocol.h"
#import "SBDashBoardViewPresenting-Protocol.h"

@protocol SBDashBoardViewControllerProtocol;

@protocol SBDashBoardPageViewControllerProtocol <SBDashBoardViewPresenting, SBApplicationHosting>
+ (unsigned long long)requiredCapabilities;
+ (_Bool)isAvailableForConfiguration;
@property(readonly, nonatomic) _Bool authenticated;
@property(nonatomic, getter=isTransitioning) _Bool transitioning;
@property(nonatomic) __weak id <SBDashBoardViewControllerProtocol> dashBoardViewController;

@optional
- (double)listInsetX;
- (double)customListWidth;
- (unsigned long long)listWidthStrategy;
- (unsigned long long)listLayout;
- (double)dateTimeInsetX;
- (unsigned long long)dateTimeLayout;
@end

