//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWallpaperEffectView.h"

@class SBUIBackgroundView;

@interface SBDashBoardWallpaperEffectView : SBWallpaperEffectView
{
    SBUIBackgroundView *_backgroundView;
}

- (void).cxx_destruct;
- (void)setBackgroundStyle:(long long)arg1;
- (void)layoutSubviews;
- (void)didAddSubview:(id)arg1;
- (id)initWithWallpaperVariant:(long long)arg1 transformOptions:(unsigned long long)arg2;

@end

