//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDashBoardQuickActionsButton;

@protocol SBDashBoardQuickActionsDelegate <NSObject>
- (void)touchEndedForButton:(SBDashBoardQuickActionsButton *)arg1;
- (void)fireActionForButton:(SBDashBoardQuickActionsButton *)arg1;
- (void)touchBeganForButton:(SBDashBoardQuickActionsButton *)arg1;
- (_Bool)isPortrait;
- (_Bool)allowsCameraPress;
- (_Bool)hasCamera;
- (_Bool)allowsFlashlight;
- (_Bool)hasFlashlight;
@end

