//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICoverSheetButton.h>

@class _UILegibilitySettings;

@interface SBDashBoardQuickActionsButton : UICoverSheetButton
{
    _Bool _permitted;
    long long _type;
    _UILegibilitySettings *_legibilitySettings;
}

@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) _Bool permitted; // @synthesize permitted=_permitted;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)_imageWithName:(id)arg1;
- (id)_buttonImageNameForSelected:(_Bool)arg1;
- (id)_statisticsIdentifierForType;
- (id)_accessoryTitleForType;
- (void)_updateStyle;
- (void)setSelected:(_Bool)arg1;
- (id)initWithType:(long long)arg1;

@end

