//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBDashBoardNotificationVersusPagingScrollSettings : SBUISettings
{
    _Bool _colorsBackground;
    double _leadingInset;
    double _trailingInset;
}

+ (id)settingsControllerModule;
@property(nonatomic) double trailingInset; // @synthesize trailingInset=_trailingInset;
@property(nonatomic) double leadingInset; // @synthesize leadingInset=_leadingInset;
@property(nonatomic) _Bool colorsBackground; // @synthesize colorsBackground=_colorsBackground;
- (void)setDefaultValues;

@end

