//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBHomeButtonSuppressAfterUnlockRecognizer-Protocol.h"

@class BSTimer, NSString;
@protocol SBHomeButtonSuppressAfterUnlockRecognizerDelegate;

@interface SBDashBoardHomeButtonSuppressAfterUnlockRecognizer : NSObject <SBHomeButtonSuppressAfterUnlockRecognizer>
{
    id <SBHomeButtonSuppressAfterUnlockRecognizerDelegate> _delegate;
    BSTimer *_timer;
    _Bool _done;
}

@property(nonatomic) __weak id <SBHomeButtonSuppressAfterUnlockRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_timerFired;
- (void)_invalidateTimer;
- (void)_startTimer;
- (void)_requestEndOfSuppression;
- (void)handleBiometricEvent:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

