//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class UIImage;

@interface SBDarkeningImageView : UIImageView
{
    UIImage *_baseImage;
    double _brightness;
}

- (void).cxx_destruct;
- (id)description;
- (void)setImage:(id)arg1 brightness:(double)arg2;
@property(nonatomic) double brightness;
- (void)setImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

