//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewBase.h"

@class NSArray;

@interface SBDashBoardRegionsDebugView : SBDashBoardViewBase
{
    NSArray *_regions;
}

@property(retain, nonatomic) NSArray *regions; // @synthesize regions=_regions;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

