//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MTMaterialView, UIColor;

@interface SBDashBoardPasscodeBackgroundView : UIView
{
    UIColor *_reduceTransparencyBackingColor;
    MTMaterialView *_materialView;
    UIView *_lightenSourceOverView;
    UIView *_plusDView;
    UIView *_reduceTransparencyTintingView;
    UIView *_reduceTransparencyBackingView;
}

@property(retain, nonatomic) UIView *reduceTransparencyBackingView; // @synthesize reduceTransparencyBackingView=_reduceTransparencyBackingView;
@property(retain, nonatomic) UIView *reduceTransparencyTintingView; // @synthesize reduceTransparencyTintingView=_reduceTransparencyTintingView;
@property(retain, nonatomic) UIView *plusDView; // @synthesize plusDView=_plusDView;
@property(retain, nonatomic) UIView *lightenSourceOverView; // @synthesize lightenSourceOverView=_lightenSourceOverView;
@property(retain, nonatomic) MTMaterialView *materialView; // @synthesize materialView=_materialView;
@property(retain, nonatomic) UIColor *reduceTransparencyBackingColor; // @synthesize reduceTransparencyBackingColor=_reduceTransparencyBackingColor;
- (void).cxx_destruct;
- (void)_setPlusDBackgroundColorWithWeighting:(double)arg1;
- (void)setWeighting:(double)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

