//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBLockScreenActionContext;

@interface SBDashBoardAction : NSObject
{
    long long _type;
    SBLockScreenActionContext *_context;
}

+ (id)actionWithContext:(id)arg1;
+ (id)actionWithType:(long long)arg1;
@property(retain, nonatomic) SBLockScreenActionContext *context; // @synthesize context=_context;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;

@end

