//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBBiometricUnlockBehavior-Protocol.h"
#import "SBMesaUnlockTriggerDelegate-Protocol.h"

@class NSString, SBLockScreenPearlSettings, SBMesaUnlockTrigger;
@protocol SBBiometricUnlockBehaviorDelegate;

@interface SBDashBoardPearlUnlockBehavior : NSObject <SBMesaUnlockTriggerDelegate, SBBiometricUnlockBehavior>
{
    SBLockScreenPearlSettings *_pearlSettings;
    id <SBBiometricUnlockBehaviorDelegate> _biometricUnlockBehaviorDelegate;
    SBMesaUnlockTrigger *_trigger;
}

@property(retain, nonatomic, getter=_trigger, setter=_setTrigger:) SBMesaUnlockTrigger *trigger; // @synthesize trigger=_trigger;
@property(nonatomic) __weak id <SBBiometricUnlockBehaviorDelegate> biometricUnlockBehaviorDelegate; // @synthesize biometricUnlockBehaviorDelegate=_biometricUnlockBehaviorDelegate;
- (void).cxx_destruct;
- (void)_handlePearlFailure;
- (id)_feedbackForBioUnlockEventThatWasSpontaneous:(_Bool)arg1;
- (id)_feedbackForPasscodeEvent;
- (id)_feedbackForFailureSettings:(id)arg1;
- (void)mesaUnlockTriggerFired:(id)arg1;
- (void)handleBiometricEvent:(unsigned long long)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)initWithPearlSettings:(id)arg1 andUnlockTrigger:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

