//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDataPlanAlertItem.h"

#import "SBDataPlanAlertActions-Protocol.h"

@class NSURL;

@interface SBDataPlanAccountAlertItem : SBDataPlanAlertItem <SBDataPlanAlertActions>
{
    NSURL *_accountURL;
}

+ (id)nowButtonTitle;
+ (id)laterButtonTitle;
@property(copy, nonatomic) NSURL *accountURL; // @synthesize accountURL=_accountURL;
- (void).cxx_destruct;
- (void)takeAction;
- (void)notNow;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (id)initWithAccountURL:(id)arg1;

@end

