//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, SBDashBoardHomeAffordanceView, SBHomeGrabberSettings, UIView;

@interface SBDashBoardHomeAffordanceViewController : UIViewController
{
    UIView *_counterRotationView;
    NSMutableArray *_rotationWrapperViews;
    long long _orientation;
    SBHomeGrabberSettings *_settings;
    SBDashBoardHomeAffordanceView *_homeAffordanceView;
    struct CGPoint _homeAffordanceOffset;
}

@property(nonatomic) struct CGPoint homeAffordanceOffset; // @synthesize homeAffordanceOffset=_homeAffordanceOffset;
@property(readonly, nonatomic) SBDashBoardHomeAffordanceView *homeAffordanceView; // @synthesize homeAffordanceView=_homeAffordanceView;
- (void).cxx_destruct;
- (id)_addWrapperViewWithOrientation:(long long)arg1;
- (struct CGRect)_homeAffordanceRestingFrame;
- (void)_layoutHomeAffordance;
- (void)setLegibilitySettings:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

