//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBWallpaperObserver-Protocol.h"

@class NSString, SBWallpaperController;
@protocol SBDashBoardLegibilityProviderDelegate;

@interface SBDashBoardLegibilityProvider : NSObject <SBWallpaperObserver>
{
    id <SBDashBoardLegibilityProviderDelegate> _delegate;
    SBWallpaperController *_wallpaperController;
}

@property(retain, nonatomic) SBWallpaperController *wallpaperController; // @synthesize wallpaperController=_wallpaperController;
@property(nonatomic) __weak id <SBDashBoardLegibilityProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_notifyDelegate;
- (id)_wallpaperLegibilitySettings;
- (void)wallpaperDidChangeForVariant:(long long)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2;
- (id)currentLegibilitySettings;
- (id)initWithWallpaperController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

