//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardParticipating-Protocol.h"

@protocol SBDashBoardViewTransitionSource;

@protocol SBDashBoardViewTransitioning <SBDashBoardParticipating>
- (void)transitionSource:(id <SBDashBoardViewTransitionSource>)arg1 didEndWithContext:(CDStruct_7238a68f)arg2;
- (void)transitionSource:(id <SBDashBoardViewTransitionSource>)arg1 didUpdateTransitionWithContext:(CDStruct_7238a68f)arg2;
- (void)transitionSource:(id <SBDashBoardViewTransitionSource>)arg1 willBeginWithType:(long long)arg2;
@end

