//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDashBoardBehavior, SBDashBoardViewController;

@protocol SBDashBoardViewControllerObserver <NSObject>

@optional
- (void)dashBoardControllerDidDismissPasscodeLockView:(SBDashBoardViewController *)arg1;
- (void)dashBoardControllerDidPresentModalView:(SBDashBoardViewController *)arg1;
- (void)dashBoardControllerExternalLockProviderStateDidChange:(SBDashBoardViewController *)arg1;
- (void)dashBoardController:(SBDashBoardViewController *)arg1 didChangeActiveBehavior:(SBDashBoardBehavior *)arg2;
@end

