//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBApplicationSceneEntity.h"

@class SBDeviceApplicationSceneHandle;

@interface SBDeviceApplicationSceneEntity : SBApplicationSceneEntity
{
}

- (id)deviceApplicationSceneEntity;
- (_Bool)isDeviceApplicationSceneEntity;
- (long long)_mainDisplayPreferredInterfaceOrientation;
- (void)_setMainDisplayPreferredInterfaceOrientation:(long long)arg1;
- (Class)viewControllerClass;
- (_Bool)_supportsLayoutRole:(long long)arg1;
- (_Bool)wantsExclusiveForeground;
- (_Bool)supportsPresentationAtAnySize;
- (id)initWithApplicationForMainSecureDisplay:(id)arg1;
- (id)initWithApplicationForMainDisplay:(id)arg1;
- (id)initWithApplicationSceneHandle:(id)arg1;
- (id)initWithApplication:(id)arg1 sceneHandleProvider:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle; // @dynamic sceneHandle;

@end

