//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBApplicationSceneViewControlling-Protocol.h"

@class SBDeviceApplicationSceneHandle, SBHomeGrabberView;

@protocol SBDeviceApplicationSceneViewControlling <SBApplicationSceneViewControlling>
@property(readonly, nonatomic) SBHomeGrabberView *homeGrabberView;
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle;
- (void)didEndTransitionToVisible:(_Bool)arg1;
- (void)willBeginTransitionToVisible:(_Bool)arg1;
@end

