//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBBaseStatusBarChangeAssertion.h"

@interface SBDisableAppStatusBarAlphaChangesAssertion : SBBaseStatusBarChangeAssertion
{
}

- (void)invalidate;
- (void)dealloc;
- (id)initWithReason:(id)arg1;

@end

