//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIAnimationController.h"

@interface SBDismissOverlaysAnimationController : SBUIAnimationController
{
    unsigned long long _dismissOptions;
}

+ (unsigned long long)_overlaysToDismissForOptions:(unsigned long long)arg1;
+ (_Bool)willDismissOverlaysForDismissOptions:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long dismissOptions; // @synthesize dismissOptions=_dismissOptions;
- (id)animationSettings;
- (void)_startAnimation;
- (_Bool)_canBeInterrupted;
- (id)initWithTransitionContextProvider:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

