//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSleepWakeHardwareButtonInteraction.h"

@class SBHIDUILockAssertion;

@interface SBDoubleClickSleepWakeHardwareButtonInteraction : SBSleepWakeHardwareButtonInteraction
{
    SBHIDUILockAssertion *_proxLockAssertion;
}

@property(retain, nonatomic) SBHIDUILockAssertion *proxLockAssertion; // @synthesize proxLockAssertion=_proxLockAssertion;
- (void).cxx_destruct;
- (void)_cancelPreviousResumeProxRequests;
- (void)_resumeProxAfterMultiplePressIntervalForReason:(id)arg1;
- (void)_resumeProxForReason:(id)arg1;
- (void)_suspendProx;
- (void)_performWake;
- (void)_performSleep;
- (void)observeSinglePressDidFail;
- (void)observeFinalPressUp;
- (_Bool)consumeSecondPressDown;
- (_Bool)consumeInitialPressUp;
- (_Bool)consumeInitialPressDown;

@end

