//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBLeafIcon.h"

@class SBApplicationPlaceholder;

@interface SBDownloadingIcon : SBLeafIcon
{
    _Bool _wasUninstalledByUser;
    SBApplicationPlaceholder *_appPlaceholder;
}

+ (id)leafIdentifierForApplicationPlaceholderBundleID:(id)arg1;
- (void).cxx_destruct;
- (id)appPlaceholder;
- (_Bool)isDownloadingIcon;
- (void)cancelDownload;
- (id)uninstallAlertBody;
- (void)setUninstalledByUser:(_Bool)arg1;
- (_Bool)uninstalledByUser;
- (void)setApplicationPlaceholder:(id)arg1;
- (void)reloadForStatusChange;
- (void)completeUninstall;
- (id)realDisplayName;
- (id)homescreenIconImage;
- (id)_darkenedIconImageForImage:(id)arg1;
- (id)gridCellImage;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithApplicationPlaceholder:(id)arg1;

@end

