//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface SBEventObserverRegistry : NSObject
{
    void *_provider;
    NSMutableDictionary *_observers;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)setValue:(_Bool)arg1 forState:(struct __CFString *)arg2;
- (void)postEventToInterestedObservers:(struct __CFString *)arg1;
- (void)removeObserverWithToken:(unsigned long long)arg1 forEvent:(id)arg2;
- (void)addObserverWithToken:(unsigned long long)arg1 forEvent:(id)arg2;
- (void)handleEvent:(id)arg1 token:(unsigned long long)arg2 action:(long long)arg3;

@end

