//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardUIServices/BSAbstractDefaultDomain.h>

@class NSArray, NSString;

@interface SBExternalGlobalDefaults : BSAbstractDefaultDomain
{
}

+ (_Bool)__useDynamicMethodResolution;
- (void)flushExternalCaches;
- (void)removeFormattedPhoneNumberFromGlobalPreferences;
@property(retain, nonatomic) NSArray *keyboards;
@property(retain, nonatomic) NSArray *languages;
@property(retain, nonatomic) NSString *locale;
- (id)init;

@end

