//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

@protocol SBFailureNotifyingTapGestureRecognizerDelegate;

@interface SBFailureNotifyingTapGestureRecognizer : UITapGestureRecognizer
{
}

- (void)setState:(long long)arg1;
@property(nonatomic) __weak id <SBFailureNotifyingTapGestureRecognizerDelegate> delegate;

@end

