//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBFolderBackgroundView;

@interface SBFloatyFolderBackgroundClipView : UIView
{
    SBFolderBackgroundView *_backgroundView;
}

@property(readonly, nonatomic) SBFolderBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
@property(nonatomic) double cornerRadius;
@property(nonatomic) unsigned long long backgroundEffect;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

