//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFluidSwitcherGesture, SBFluidSwitcherGestureWorkspaceTransaction;

@protocol SBFluidSwitcherGestureWorkspaceTransactionDelegate <NSObject>
- (void)fluidSwitcherGestureTransaction:(SBFluidSwitcherGestureWorkspaceTransaction *)arg1 didEndGesture:(SBFluidSwitcherGesture *)arg2;
- (void)fluidSwitcherGestureTransaction:(SBFluidSwitcherGestureWorkspaceTransaction *)arg1 didUpdateGesture:(SBFluidSwitcherGesture *)arg2;
- (void)fluidSwitcherGestureTransaction:(SBFluidSwitcherGestureWorkspaceTransaction *)arg1 didBeginGesture:(SBFluidSwitcherGesture *)arg2;
@end

