//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFloatingApplicationController;

@protocol SBFloatingApplicationControllerInternalDelegate <NSObject>

@optional
- (void)floatingApplicationControllerRelinquishInterfaceOrientationLock:(SBFloatingApplicationController *)arg1;
- (void)floatingApplicationControllerAcquireInterfaceOrientationLock:(SBFloatingApplicationController *)arg1;
- (void)floatingApplicationController:(SBFloatingApplicationController *)arg1 needsVisibleWindow:(_Bool)arg2;
@end

