//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconListView.h"

@interface SBFolderIconListView : SBIconListView
{
}

+ (unsigned long long)maxVisibleIconRowsInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconColumnsForInterfaceOrientation:(long long)arg1;
- (long long)iconLocation;
- (double)sideIconInset;
- (double)bottomIconInset;
- (double)topIconInset;

@end

