//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughView.h>

@class SBFolderView, SBIconLayoutOverrideStrategy, UIView;

@interface SBFolderContainerView : SBFTouchPassThroughView
{
    double _statusBarHeight;
    SBIconLayoutOverrideStrategy *_iconLayoutOverrideStrategy;
    SBFolderView *_folderView;
    SBFolderContainerView *_childFolderContainerView;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SBFolderView *folderView; // @synthesize folderView=_folderView;
@property(retain, nonatomic) SBIconLayoutOverrideStrategy *iconLayoutOverrideStrategy; // @synthesize iconLayoutOverrideStrategy=_iconLayoutOverrideStrategy;
@property(nonatomic) double statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGRect)_frameForFolderView:(id)arg1;
@property(retain, nonatomic) SBFolderContainerView *childFolderContainerView;
- (id)initWithFolderView:(id)arg1 statusBarHeight:(double)arg2;

@end

