//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBWindow, UIScreen, UIView;

@interface SBFolderControllerAnimationContext : NSObject
{
    UIScreen *_screen;
    SBWindow *_animationWindow;
    UIView *_fallbackIconContainer;
}

+ (id)contextWithScreen:(id)arg1 animationWindow:(id)arg2 fallbackIconContainer:(id)arg3;
@property(readonly, nonatomic) UIView *fallbackIconContainer; // @synthesize fallbackIconContainer=_fallbackIconContainer;
@property(readonly, nonatomic) SBWindow *animationWindow; // @synthesize animationWindow=_animationWindow;
@property(readonly, nonatomic) UIScreen *screen; // @synthesize screen=_screen;
- (void).cxx_destruct;
- (id)initWithScreen:(id)arg1 animationWindow:(id)arg2 fallbackIconContainer:(id)arg3;

@end

