//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIVisualEffectView;
@protocol SBFolderBackgroundViewDelegate;

@interface SBFolderBackgroundView : UIView
{
    UIView *_tintView;
    UIVisualEffectView *_blurView;
    double _continuousCornerRadius;
    id <SBFolderBackgroundViewDelegate> _delegate;
    unsigned long long _effect;
    unsigned long long _currentEffect;
}

+ (double)cornerRadiusToInsetContent;
+ (struct CGSize)folderBackgroundSize;
+ (void)warmupIfNecessary;
@property(nonatomic) unsigned long long currentEffect; // @synthesize currentEffect=_currentEffect;
@property(nonatomic) unsigned long long effect; // @synthesize effect=_effect;
@property(nonatomic) __weak id <SBFolderBackgroundViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_blurEffect;
- (id)_tintViewBackgroundColorAtFullAlpha;
- (_Bool)_hasLowQualityBackground;
- (void)updateTintEffectColor;
- (void)_updateCurrentEffect;
@property(readonly, nonatomic) unsigned long long concreteEffect;
- (void)_reduceTransparencyChanged;
- (void)_setContinuousCornerRadius:(double)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

