//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBIconAccessoryInfoProvider-Protocol.h"

@class NSString;

@interface SBForceTouchAppIconInfoProvider : NSObject <SBIconAccessoryInfoProvider>
{
}

@property(readonly, nonatomic) long long continuityBadgeType;
@property(readonly, nonatomic, getter=isHighlighted) _Bool highlighted;
@property(readonly, nonatomic) long long location;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

