//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFWallpaperConfigurationManager;

@protocol SBFWallpaperConfigurationManagerDelegate <NSObject>
- (void)wallpaperConfigurationManager:(SBFWallpaperConfigurationManager *)arg1 didChangeWallpaperConfigurationForVariants:(long long)arg2;

@optional
- (_Bool)wallpaperConfigurationManager:(SBFWallpaperConfigurationManager *)arg1 isVideoSupportedForVariant:(long long)arg2;
@end

