//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFWallpaperView;

@protocol SBFWallpaperViewInternalObserver <NSObject>
- (void)wallpaperViewDidChangeWantsRasterization:(SBFWallpaperView *)arg1;
- (void)wallpaperView:(SBFWallpaperView *)arg1 didChangeZoomFactor:(double)arg2;
- (void)wallpaperViewDidInvalidateGeometry:(SBFWallpaperView *)arg1;
- (void)wallpaperViewDidInvalidateBlurs:(SBFWallpaperView *)arg1;
@end

