//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface SBGradientView : UIView
{
    NSArray *_colors;
}

+ (Class)layerClass;
@property(copy, nonatomic) NSArray *colors; // @synthesize colors=_colors;
- (void).cxx_destruct;
@property struct CGPoint endPoint;
@property struct CGPoint startPoint;
@property(copy, nonatomic) NSArray *locations;
- (id)color;

@end

