//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBGrabberTongue, UIPanGestureRecognizer, UITouch;

@protocol SBGrabberTongueDelegate <NSObject>
- (_Bool)grabberTongue:(SBGrabberTongue *)arg1 shouldShowTongueOnFirstSwipeWithEdgeLocation:(double)arg2;
- (_Bool)grabberTongueOrPullEnabled:(SBGrabberTongue *)arg1;

@optional
- (_Bool)shouldSuppressTongueViewForGrabberTongue:(SBGrabberTongue *)arg1;
- (UIPanGestureRecognizer *)customGestureRecognizerForGrabberTongue:(SBGrabberTongue *)arg1;
- (void)grabberTongueDidPresentInteractively:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueWillPresentInteractively:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueDidDismiss:(SBGrabberTongue *)arg1;
- (void)grabberTongueWillDismiss:(SBGrabberTongue *)arg1;
- (void)grabberTongueWillPresent:(SBGrabberTongue *)arg1;
- (void)grabberTongueCanceledPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueEndedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueUpdatedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueBeganPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (_Bool)grabberTongueHonorsAmbiguousActivationMargin:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongue:(SBGrabberTongue *)arg1 shouldAllowSecondSwipeWithEdgeLocation:(double)arg2;
- (_Bool)grabberTongue:(SBGrabberTongue *)arg1 shouldReceiveTouch:(UITouch *)arg2;
@end

