//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, SBHomeGrabberSettings, SBHomeGrabberView;

@interface SBHomeGrabberRotationView : UIView
{
    NSMutableArray *_rotationWrapperViews;
    SBHomeGrabberSettings *_grabberSettings;
    SBHomeGrabberView *_grabberView;
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) SBHomeGrabberView *grabberView; // @synthesize grabberView=_grabberView;
- (void).cxx_destruct;
- (id)_addWrapperViewWithOrientation:(long long)arg1;
- (void)setOrientation:(long long)arg1 animated:(_Bool)arg2 rotationSettings:(id)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

