//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBHomeGrabberView;

@protocol SBHomeGrabberDelegate <NSObject>
- (_Bool)shouldAllowAutoHideForHomeGrabberView:(SBHomeGrabberView *)arg1;
- (_Bool)shouldAllowThinStyleForHomeGrabberView:(SBHomeGrabberView *)arg1;
- (double)additionalEdgeSpacingForHomeGrabberView:(SBHomeGrabberView *)arg1;
@end

