//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBHomeScreenTodayViewController;

@protocol SBHomeScreenTodayViewControllerDelegate <NSObject>
- (void)todayViewController:(SBHomeScreenTodayViewController *)arg1 dismissSearchViewWithReason:(unsigned long long)arg2;
- (void)todayViewControllerDidFocusSearchField:(SBHomeScreenTodayViewController *)arg1;
- (void)todayViewController:(SBHomeScreenTodayViewController *)arg1 didEndInteractivePullToSearchSuccessfully:(_Bool)arg2;
- (void)todayViewController:(SBHomeScreenTodayViewController *)arg1 didUpdateInteractivePullToSearchWithProgress:(double)arg2;
- (void)todayViewControllerDidBeginInteractivePullToSearch:(SBHomeScreenTodayViewController *)arg1;
- (_Bool)todayViewControllerCanBeginInteractivePullToSearch:(SBHomeScreenTodayViewController *)arg1;
@end

