//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBMesaUnlockTrigger.h"

@class BSTimer;

@interface SBHomeButtonPressSpeedMesaUnlockTrigger : SBMesaUnlockTrigger
{
    BSTimer *_slowPressTimer;
    _Bool _bioUnlockOccurred;
    _Bool _buttonIsDown;
    _Bool _fingerIsOn;
    _Bool _timerFired;
    double _slowPressDuration;
}

@property(retain, nonatomic, getter=_slowPressTimer, setter=_setSlowPressTimer:) BSTimer *slowPressTimer; // @synthesize slowPressTimer=_slowPressTimer;
@property(nonatomic) double slowPressDuration; // @synthesize slowPressDuration=_slowPressDuration;
- (void).cxx_destruct;
- (_Bool)_isPrimed;
- (void)_evaluateUnlock;
- (_Bool)_isTimerRunning;
- (void)_timerFired;
- (void)_cancelTimer;
- (void)_startTimer;
- (void)fingerOff;
- (void)menuButtonUp;
- (void)menuButtonDown;
- (void)screenOff;
- (_Bool)bioUnlock;
- (id)succinctDescriptionBuilder;
- (id)description;
- (id)init;

@end

