//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UISettings.h>

@class SBHomeGrabberSettings;

@interface SBHomeScreenSettings : _UISettings
{
    _Bool _showPopOversEverywhere;
    _Bool _reordersOutsideOfEditMode;
    _Bool _showsGhostIconsBeforeEditing;
    double _editModeDragThreshold;
    double _popoverDelay;
    double _editModeDelay;
    SBHomeGrabberSettings *_grabberSettings;
}

+ (id)settingsControllerModule;
@property(retain) SBHomeGrabberSettings *grabberSettings; // @synthesize grabberSettings=_grabberSettings;
@property(nonatomic) double editModeDelay; // @synthesize editModeDelay=_editModeDelay;
@property(nonatomic) double popoverDelay; // @synthesize popoverDelay=_popoverDelay;
@property(nonatomic) _Bool showsGhostIconsBeforeEditing; // @synthesize showsGhostIconsBeforeEditing=_showsGhostIconsBeforeEditing;
@property(nonatomic) double editModeDragThreshold; // @synthesize editModeDragThreshold=_editModeDragThreshold;
@property(nonatomic) _Bool reordersOutsideOfEditMode; // @synthesize reordersOutsideOfEditMode=_reordersOutsideOfEditMode;
@property(nonatomic) _Bool showPopOversEverywhere; // @synthesize showPopOversEverywhere=_showPopOversEverywhere;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

