//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIApplicationSceneClientSettings, UIApplicationSceneSettings;

@interface SBHostedAppClientSettingObserverContext : NSObject
{
    UIApplicationSceneSettings *_settings;
    UIApplicationSceneClientSettings *_updatedClientSettings;
}

@property(retain, nonatomic) UIApplicationSceneClientSettings *updatedClientSettings; // @synthesize updatedClientSettings=_updatedClientSettings;
@property(retain, nonatomic) UIApplicationSceneSettings *settings; // @synthesize settings=_settings;
- (void).cxx_destruct;

@end

