//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable, SBCountedMap;

@interface SBIconLabelImageCache : NSObject
{
    NSMapTable *_imageParametersToImageMap;
    SBCountedMap *_map;
    CDUnknownBlockType _creationBlock;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType creationBlock; // @synthesize creationBlock=_creationBlock;
@property(readonly, nonatomic) SBCountedMap *map; // @synthesize map=_map;
@property(retain, nonatomic) NSMapTable *imageParametersToImageMap; // @synthesize imageParametersToImageMap=_imageParametersToImageMap;
- (void).cxx_destruct;
- (_Bool)checkinLabelImage:(id)arg1;
- (id)checkoutLabelImageForParameters:(id)arg1;
- (id)init;
- (id)initWithCreationBlock:(CDUnknownBlockType)arg1;

@end

