//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBIcon, SBIconView, SBIconViewMap;

@interface SBIconRotationContainer : UIView
{
    struct SBIconCoordinate _coordinate;
    SBIconViewMap *_viewMap;
    SBIconView *_startView;
    SBIconView *_endView;
    struct CGPoint _wallpaperRelativeImageCenter;
    long long _location;
}

@property(readonly, nonatomic) long long location; // @synthesize location=_location;
@property(nonatomic) struct CGPoint wallpaperRelativeImageCenter; // @synthesize wallpaperRelativeImageCenter=_wallpaperRelativeImageCenter;
@property(readonly, nonatomic) struct SBIconCoordinate coordinate; // @synthesize coordinate=_coordinate;
- (void).cxx_destruct;
- (void)crossfadeWithDuration:(double)arg1;
- (void)prepareToCrossfade;
@property(readonly, nonatomic) struct CGPoint iconImageCenter;
@property(readonly, nonatomic) SBIcon *endIcon;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 startIcon:(id)arg2 endIcon:(id)arg3 viewMap:(id)arg4 coordinate:(struct SBIconCoordinate)arg5 location:(long long)arg6;

@end

