//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBIconLabelImageParameters, UIImage, _UILegibilitySettings;

@protocol SBIconLabelView
@property(retain, nonatomic) UIImage *image;
- (void)updateIconLabelWithSettings:(_UILegibilitySettings *)arg1 imageParameters:(SBIconLabelImageParameters *)arg2;
- (id)initWithSettings:(_UILegibilitySettings *)arg1;
@end

