//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBIconListView;

@protocol SBIconListLayoutDelegate <NSObject>
- (struct CGPoint)iconListView:(SBIconListView *)arg1 originForIconCoordinate:(struct SBIconCoordinate)arg2 proposedOrigin:(struct CGPoint)arg3;

@optional
- (void)iconListViewIsNotDisplayingAnyIcons:(SBIconListView *)arg1;
@end

