//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBReusableViewMap.h"

@interface SBIconLabelAccessoryViewMap : SBReusableViewMap
{
}

+ (Class)viewClassForLabelAccessoryType:(long long)arg1;
+ (struct CGSize)labelAccessoryViewSizeForType:(long long)arg1;
- (id)viewForLabelAccessoryType:(long long)arg1;

@end

