//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBFolderContainerView.h"

@interface SBIconContentView : SBFolderContainerView
{
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void)didAddSubview:(id)arg1;
- (id)initWithOrientation:(long long)arg1 statusBarHeight:(double)arg2;

@end

