//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBIconDraggingEditContext : NSObject
{
    _Bool _enteredScreenLocationNeedsUpdate;
    id _draggingUniqueIdentifier;
    struct CGPoint _enteredScreenLocation;
}

@property(nonatomic) _Bool enteredScreenLocationNeedsUpdate; // @synthesize enteredScreenLocationNeedsUpdate=_enteredScreenLocationNeedsUpdate;
@property(nonatomic) struct CGPoint enteredScreenLocation; // @synthesize enteredScreenLocation=_enteredScreenLocation;
@property(retain, nonatomic) id draggingUniqueIdentifier; // @synthesize draggingUniqueIdentifier=_draggingUniqueIdentifier;
- (void).cxx_destruct;

@end

