//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFolder, SBIconModel;

@protocol SBIconStateUnarchiveContext <NSObject>
- (void)_noteNodeIdentifierWasUnarchived:(id)arg1;
- (_Bool)_isNodeIdentifierAlreadyUnarchived:(id)arg1;
- (void)_noteSignificantDeviation;
- (void)_noteRepresentationIsCorrupted;
- (long long)_currentParseDepth;
- (void)_noteExitedNode;
- (void)_noteEnteredNode;
- (SBFolder *)_popFolder;
- (SBFolder *)_currentFolder;
- (void)_pushFolder:(SBFolder *)arg1;
- (SBIconModel *)_iconSource;
@end

