//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAnalyticsStateMachineEventHandler.h"

@class PETGoalConversionEventTracker;

@interface SBIconLaunchMetric : SBAnalyticsStateMachineEventHandler
{
    PETGoalConversionEventTracker *_trackerV1;
    PETGoalConversionEventTracker *_trackerV2;
    _Bool _isFolder;
    long long _iconLocation;
    unsigned long long _layoutLocation;
}

- (void).cxx_destruct;
- (id)init;
- (void)_processAndReportLaunchedEventPayload:(id)arg1;
- (void)_processAndReportTappedEventPayload:(id)arg1;

@end

