//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SBIconAnimationContext : NSObject
{
    double _delay;
    double _fraction;
    CDUnknownBlockType _completion;
    NSString *_identifier;
}

@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) double fraction; // @synthesize fraction=_fraction;
@property(nonatomic) double delay; // @synthesize delay=_delay;
- (void).cxx_destruct;
- (void)invalidate;
- (void)dealloc;
- (id)initWithNotificationIdentifier:(id)arg1;

@end

