//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBReusableViewMap.h"

@interface SBIconAccessoryViewMap : SBReusableViewMap
{
}

- (void)recycleView:(id)arg1;
- (id)viewOfClass:(Class)arg1;

@end

