//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBIconColorSettings : SBUISettings
{
    _Bool _blurryFolderIcons;
    _Bool _blurryCloseBoxes;
    _Bool _suppressJitter;
    _Bool _closeBoxesEverywhere;
    double _maxSaturationBoost;
    double _maxSaturation;
    double _maxBrightnessBoost;
    double _maxBrightness;
    double _colorAlpha;
    double _whiteAlpha;
}

+ (id)settingsControllerModule;
@property(nonatomic) _Bool closeBoxesEverywhere; // @synthesize closeBoxesEverywhere=_closeBoxesEverywhere;
@property(nonatomic) _Bool suppressJitter; // @synthesize suppressJitter=_suppressJitter;
@property(nonatomic) double whiteAlpha; // @synthesize whiteAlpha=_whiteAlpha;
@property(nonatomic) double colorAlpha; // @synthesize colorAlpha=_colorAlpha;
@property(nonatomic) double maxBrightness; // @synthesize maxBrightness=_maxBrightness;
@property(nonatomic) double maxBrightnessBoost; // @synthesize maxBrightnessBoost=_maxBrightnessBoost;
@property(nonatomic) double maxSaturation; // @synthesize maxSaturation=_maxSaturation;
@property(nonatomic) double maxSaturationBoost; // @synthesize maxSaturationBoost=_maxSaturationBoost;
@property(nonatomic) _Bool blurryCloseBoxes; // @synthesize blurryCloseBoxes=_blurryCloseBoxes;
@property(nonatomic) _Bool blurryFolderIcons; // @synthesize blurryFolderIcons=_blurryFolderIcons;
- (void)setDefaultValues;

@end

