//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIdleTimerBase.h"

#import "SBIdleTimerObserving-Protocol.h"

@class NSString;
@protocol SBIdleTimer;

@interface SBIdleTimerProxy : SBIdleTimerBase <SBIdleTimerObserving>
{
    id <SBIdleTimer> _sourceTimer;
}

+ (id)disabledIdleTimerProxy;
@property(retain, nonatomic) id <SBIdleTimer> sourceTimer; // @synthesize sourceTimer=_sourceTimer;
- (void).cxx_destruct;
- (void)_logExpirationTimeout:(double)arg1;
- (void)setActivated:(_Bool)arg1;
- (_Bool)isActivated;
- (void)idleTimerDidResetForUserAttention:(id)arg1;
- (void)idleTimerDidWarn:(id)arg1;
- (void)idleTimerDidExpire:(id)arg1;
- (void)idleTimerDidRefresh:(id)arg1;
- (void)reset;
- (_Bool)isDisabled;
- (id)initWithIdleTimerSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

