//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBIrisWallpaperSettings : SBUISettings
{
    _Bool _orbCancelsScroll;
    _Bool _scrollCancelsOrb;
    _Bool _irisLoopFadesOutUI;
}

+ (id)settingsControllerModule;
@property(nonatomic) _Bool irisLoopFadesOutUI; // @synthesize irisLoopFadesOutUI=_irisLoopFadesOutUI;
@property(nonatomic) _Bool scrollCancelsOrb; // @synthesize scrollCancelsOrb=_scrollCancelsOrb;
@property(nonatomic) _Bool orbCancelsScroll; // @synthesize orbCancelsScroll=_orbCancelsScroll;
- (void)setDefaultValues;

@end

