//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BSDescriptionProviding-Protocol.h"

@class NSSet, NSString;

@interface SBLayoutState : NSObject <BSDescriptionProviding>
{
    long long _interfaceOrientation;
    long long _elementInterfaceOrientation;
    NSSet *_elements;
}

+ (long long)_defaultInterfaceOrientation;
@property(readonly, nonatomic) NSSet *elements; // @synthesize elements=_elements;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (_Bool)isEqual:(id)arg1 withRole:(long long)arg2;
- (id)elementWithIdentifier:(id)arg1;
- (id)elementWithRole:(long long)arg1;
- (_Bool)layoutContainsRole:(long long)arg1;
@property(readonly, nonatomic) long long elementInterfaceOrientation;
@property(readonly, nonatomic) long long interfaceOrientation;
- (id)init;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3;
- (id)appLayout;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

