//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, NSString, SBActivationSettings, SBLeafIcon, UIImage;

@protocol SBLeafIconDataSource <NSObject>
- (_Bool)icon:(SBLeafIcon *)arg1 launchFromLocation:(long long)arg2 context:(id)arg3 activationSettings:(SBActivationSettings *)arg4 actions:(NSSet *)arg5;
- (_Bool)iconAllowsLaunch:(SBLeafIcon *)arg1;
- (_Bool)iconCompleteUninstall:(SBLeafIcon *)arg1;
- (_Bool)iconSupportsUninstall:(SBLeafIcon *)arg1;
- (long long)iconLabelAccessoryType:(SBLeafIcon *)arg1;
- (long long)iconAccessoryType:(SBLeafIcon *)arg1;
- (NSString *)iconFormattedAccessoryString:(SBLeafIcon *)arg1;
- (id)iconBadgeNumberOrString:(SBLeafIcon *)arg1;
- (_Bool)iconProgressIsPaused:(SBLeafIcon *)arg1;
- (double)iconProgressPercent:(SBLeafIcon *)arg1;
- (long long)iconProgressState:(SBLeafIcon *)arg1;
- (_Bool)iconCanTightenLabel:(SBLeafIcon *)arg1;
- (_Bool)iconCanEllipsizeLabel:(SBLeafIcon *)arg1;
- (NSString *)iconDisplayName:(SBLeafIcon *)arg1 forLocation:(long long)arg2;
- (UIImage *)icon:(SBLeafIcon *)arg1 defaultImageWithFormat:(int)arg2;
- (UIImage *)icon:(SBLeafIcon *)arg1 imageWithFormat:(int)arg2;
- (unsigned long long)iconPriority:(SBLeafIcon *)arg1;
@end

