//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconImageView.h"

@interface SBLiveIconImageView : SBIconImageView
{
}

- (id)snapshot;
- (void)prepareForReuse;
- (void)updateImageAnimated:(_Bool)arg1;
- (void)updateUnanimated;
- (void)updateAnimatingState;
- (void)setPaused:(_Bool)arg1;
- (_Bool)isAnimationAllowed;
- (void)setIcon:(id)arg1 location:(long long)arg2 animated:(_Bool)arg3;

@end

