//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBAutoUnlockRule-Protocol.h"

@class NSMutableSet, NSString;

@interface SBLockScreenDisabledAssertionManager : NSObject <SBAutoUnlockRule>
{
    NSMutableSet *_disableLockScreenIfPossibleAssertions;
}

- (void).cxx_destruct;
- (_Bool)shouldAutoUnlockForSource:(int)arg1;
- (_Bool)isLockScreenDisabledForAssertion;
- (void)removeLockScreenDisableAssertion:(id)arg1;
- (void)addLockScreenDisableAssertion:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

