//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBLockScreenActionContextFactory : NSObject
{
}

+ (id)sharedInstance;
- (id)lockScreenActionContextForAction:(id)arg1 fromPlugin:(id)arg2;
- (id)lockScreenActionContextForPlugin:(id)arg1;
- (id)lockScreenActionContextForAlertItem:(id)arg1;

@end

