//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFLockScreenDateSubtitleView.h>

#import "_UISettingsKeyObserver-Protocol.h"

@class NSDate, NSString;

@interface SBLockScreenTimerView : SBFLockScreenDateSubtitleView <_UISettingsKeyObserver>
{
    NSDate *_endDate;
}

- (void).cxx_destruct;
- (id)_timerFont;
- (id)_newTimerDialForSettings:(id)arg1;
- (void)_updateLegibilityStrength;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)updateTimerLabel;
- (void)setEndDate:(id)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

