//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SBMainScreenActiveInterfaceOrientationWindow, UITextView;

@interface SBLogWindowController : UIViewController
{
    UITextView *_logTextView;
    SBMainScreenActiveInterfaceOrientationWindow *_logWindow;
}

+ (id)sharedInstanceIfAvailable;
+ (id)sharedInstance;
@property(retain, nonatomic) SBMainScreenActiveInterfaceOrientationWindow *logWindow; // @synthesize logWindow=_logWindow;
@property(retain, nonatomic) UITextView *logTextView; // @synthesize logTextView=_logTextView;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

