//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class SBDashBoardVibrantWallpaperButton, SBUserSessionController;

@interface SBLockScreenLogoutButtonViewController : SBDashBoardViewControllerBase
{
    SBUserSessionController *_userSessionController;
}

+ (_Bool)isLogoutSupported;
- (void).cxx_destruct;
- (void)_buttonPressed:(id)arg1;
- (void)loadView;
@property(readonly, nonatomic) SBDashBoardVibrantWallpaperButton *button;
- (id)init;

@end

