//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUIServices/SBUIEmergencyCallHostViewController.h>

@protocol SBLockScreenEmergencyCallViewControllerDelegate;

@interface SBLockScreenEmergencyCallViewController : SBUIEmergencyCallHostViewController
{
    id <SBLockScreenEmergencyCallViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBLockScreenEmergencyCallViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)_wallpaperStyleFromUIBackgroundStyle:(long long)arg1;
- (id)tintColorForBackgroundStyle:(long long)arg1 outBlurRadius:(double *)arg2;
- (void)setBackgroundStyle:(long long)arg1;
- (void)dismiss;
- (void)viewServiceDidTerminateWithError:(id)arg1;

@end

