//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError, NSString;

@protocol SBLoginAppSceneHosterDelegate
- (void)sceneUpdatedRotationMode:(long long)arg1;
- (void)sceneUpdatedStatusBarUserName:(NSString *)arg1;
- (void)sceneUpdatedIdleTimerMode:(long long)arg1;
- (void)sceneDeactivatedWithError:(NSError *)arg1;
@end

