//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class FBSProcessHandle, NSString, SBApplication;

@interface SBLockScreenUnlockRequest : NSObject <NSCopying>
{
    _Bool _wantsBiometricPresentation;
    _Bool _forceAlertAuthenticationUI;
    _Bool _confirmedNotInPocket;
    int _source;
    int _intent;
    NSString *_name;
    FBSProcessHandle *_process;
    SBApplication *_destinationApplication;
}

@property(nonatomic) _Bool confirmedNotInPocket; // @synthesize confirmedNotInPocket=_confirmedNotInPocket;
@property(nonatomic) _Bool forceAlertAuthenticationUI; // @synthesize forceAlertAuthenticationUI=_forceAlertAuthenticationUI;
@property(nonatomic) _Bool wantsBiometricPresentation; // @synthesize wantsBiometricPresentation=_wantsBiometricPresentation;
@property(retain, nonatomic) SBApplication *destinationApplication; // @synthesize destinationApplication=_destinationApplication;
@property(retain, nonatomic) FBSProcessHandle *process; // @synthesize process=_process;
@property(nonatomic) int intent; // @synthesize intent=_intent;
@property(nonatomic) int source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

