//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol SBLockOverlayViewControllerDelegate;

@interface SBLockOverlayViewController : UIViewController
{
    id <SBLockOverlayViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBLockOverlayViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldBeHidden;
- (id)overlayView;

@end

