//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, SBLogoutProgressAlertViewController;

@protocol SBLogoutProgressDataSource <NSObject>
- (NSArray *)pendingApplicationsForLogoutProgressAlertViewController:(SBLogoutProgressAlertViewController *)arg1;

@optional
- (NSDictionary *)debugBlockingTasksForLogoutProgressAlertViewController:(SBLogoutProgressAlertViewController *)arg1;
@end

