//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class MTTimerManager, NSDate, NSTimer;
@protocol SBLockScreenTimerViewControllerDelegate;

@interface SBLockScreenTimerViewController : SBDashBoardViewControllerBase
{
    _Bool _enabled;
    NSTimer *_updateTimer;
    NSDate *_endDate;
    MTTimerManager *_timerManager;
    id <SBLockScreenTimerViewControllerDelegate> _delegate;
}

@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <SBLockScreenTimerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_updateNextTimer;
- (void)_nextTimerChanged:(id)arg1;
- (void)_updateTimerLabelView;
- (void)_updateTimerFired;
- (void)_startTimer;
- (void)_stopTimerNotifyingDelegate:(_Bool)arg1;
- (void)_stopTimer;
- (_Bool)isEndDateValid;
- (id)timerView;
- (void)setEndDate:(id)arg1;
- (_Bool)isTimerActive;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

