//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, NSString, SBLayoutElement, SBMainDisplayLayoutState, SBMainDisplayWorkspaceAppInteractionEventSource;

@protocol SBMainDisplayWorkspaceAppInteractionEventSourceObserving <NSObject>

@optional
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 didFinishTransitionToMode:(long long)arg2 withLayoutState:(SBMainDisplayLayoutState *)arg3 activatingElement:(SBLayoutElement *)arg4 triggeredBy:(long long)arg5;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 didBeginTransitionToMode:(long long)arg2 withLayoutState:(SBMainDisplayLayoutState *)arg3 activatingElement:(SBLayoutElement *)arg4 triggeredBy:(long long)arg5;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 keyboardFocusChangedToApplication:(NSString *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 userTouchedApplication:(NSString *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 applicationsBecameVisible:(NSSet *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 applicationsBecameHidden:(NSSet *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 userQuitApplicationInSwitcher:(NSString *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 userDeletedApplications:(NSSet *)arg2;
- (void)eventSource:(SBMainDisplayWorkspaceAppInteractionEventSource *)arg1 userRemovedSuggestions:(NSSet *)arg2;
@end

