//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAppLayout, SBBestAppSuggestion;
@protocol SBMainAppSwitcherContentViewControlling;

@protocol SBMainAppSwitcherContentViewControllerDelegate <NSObject>
- (void)updateUserInteractionEnabledForSwitcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1;
- (unsigned long long)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 indexForBringingAppLayoutToFront:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 bringAppLayoutToFront:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 activatedBestAppSuggestion:(SBBestAppSuggestion *)arg2;
- (_Bool)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 canDeleteAppLayout:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 deletedAppLayout:(SBAppLayout *)arg2 forReason:(long long)arg3;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 selectedAppLayout:(SBAppLayout *)arg2;
@end

