//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBApplicationUpdateScenesTransaction, FBScene, NSSet;

@protocol SBMainScreenApplicationSceneTransactionObserver <NSObject>
- (void)mainScreenApplicationSceneDidCommit:(FBScene *)arg1;
- (void)mainScreenApplicationSceneWillCommit:(FBScene *)arg1;
- (void)mainScreenApplicationUpdateScenesTransactionCompleted:(FBApplicationUpdateScenesTransaction *)arg1;
- (void)mainScreenApplicationTransactionDidCommitSceneUpdatesForEntities:(NSSet *)arg1;
@end

