//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBLayoutState.h"

@interface SBMainDisplayLayoutState : SBLayoutState
{
    long long _spaceConfiguration;
    long long _floatingConfiguration;
    long long _unlockedEnvironmentMode;
}

+ (long long)_defaultInterfaceOrientation;
@property(readonly, nonatomic) long long unlockedEnvironmentMode; // @synthesize unlockedEnvironmentMode=_unlockedEnvironmentMode;
@property(readonly, nonatomic) long long floatingConfiguration; // @synthesize floatingConfiguration=_floatingConfiguration;
@property(readonly, nonatomic) long long spaceConfiguration; // @synthesize spaceConfiguration=_spaceConfiguration;
- (long long)interfaceOrientation;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3 spaceConfiguration:(long long)arg4 floatingConfiguration:(long long)arg5 unlockedEnvironmentMode:(long long)arg6;
- (id)transitionContextForActivatingHomeScreen;
- (id)transitionContextForActivatingAppSwitcher;
- (id)transitionContextForActivatingAppLayout:(id)arg1;
- (id)_transitionContextForDismissingRightApplication;
- (id)_transitionContextForResizingToSpaceConfiguration:(long long)arg1;
- (id)_transitionContextForDismissingLeftApplication;

@end

