//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBLayoutStateManager.h"

@class SBMainDisplaySceneManager, SBMainWorkspace, SBPlatformController, SBRecentAppLayouts;

@interface SBMainDisplayLayoutStateManager : SBLayoutStateManager
{
}

+ (Class)_layoutStateClass;
- (id)_applicationSceneEntityFromApplicationBundleIdentifier:(id)arg1;
@property(readonly, nonatomic) SBRecentAppLayouts *_recentAppLayouts;
@property(readonly, nonatomic) SBMainDisplaySceneManager *_mainDisplaySceneManager;
@property(readonly, nonatomic) SBMainWorkspace *_mainWorkspace;
@property(readonly, nonatomic) SBPlatformController *_platformController;
- (id)_layoutStateForApplicationTransitionContext:(id)arg1;
- (id)_mostRecentAppLayoutMatchingWorkspaceDisplayIdentifiers:(id)arg1;
- (id)layoutStateForApplicationTransitionContext:(id)arg1;

@end

