//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSceneLayoutWindow.h"

@interface SBMainDisplaySceneLayoutWindow : SBSceneLayoutWindow
{
}

- (_Bool)_usesWindowServerHitTesting;
- (id)_hitTest:(struct CGPoint)arg1 withEvent:(id)arg2 windowServerHitTestWindow:(id)arg3;

@end

