//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDeviceApplicationScenePlaceholderContentContext.h"

@class NSString, NSURL;

@interface SBMutableDeviceApplicationScenePlaceholderContentContext : SBDeviceApplicationScenePlaceholderContentContext
{
}


// Remaining properties
@property(nonatomic) unsigned long long preferredContentType; // @dynamic preferredContentType;
@property(nonatomic) _Bool prefersLiveXIB; // @dynamic prefersLiveXIB;
@property(copy, nonatomic) NSString *requestedLaunchIdentifier; // @dynamic requestedLaunchIdentifier;
@property(copy, nonatomic) NSURL *url; // @dynamic url;
@end

