//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAppStatusBarSettings.h"

@class NSNumber, _UILegibilitySettings;

@interface SBMutableAppStatusBarSettings : SBAppStatusBarSettings
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)applySettings:(id)arg1;
@property(nonatomic) int styleOverridesToCancel; // @dynamic styleOverridesToCancel;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @dynamic legibilitySettings;
@property(nonatomic) long long style; // @dynamic style;
@property(retain, nonatomic) NSNumber *alpha; // @dynamic alpha;
- (id)init;

@end

