//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconLabelImageParameters.h"

@class NSString, UIColor, UIFont;

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

@property(nonatomic) struct UIEdgeInsets fontLanguageInsets; // @dynamic fontLanguageInsets;
@property(nonatomic) struct UIEdgeInsets textInsets; // @dynamic textInsets;
@property(retain, nonatomic) UIColor *focusHighlightColor; // @dynamic focusHighlightColor;
@property(nonatomic) _Bool accessibilityIncreaseContrastEnabled; // @dynamic accessibilityIncreaseContrastEnabled;
@property(nonatomic) double scale; // @dynamic scale;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
@property(nonatomic) long long style; // @dynamic style;
@property(nonatomic) _Bool canUseMemoryPool; // @dynamic canUseMemoryPool;
@property(nonatomic) _Bool containsEmoji; // @dynamic containsEmoji;
@property(nonatomic) _Bool canTighten; // @dynamic canTighten;
@property(nonatomic) _Bool canEllipsize; // @dynamic canEllipsize;
@property(nonatomic) long long iconLocation; // @dynamic iconLocation;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic) struct CGSize maxSize; // @dynamic maxSize;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)copy;

@end

