//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIScrollView, UIView, UIViewController;

@protocol SBMultiplexedHostingObserver <NSObject>

@optional
- (void)textSelectionInteractionDidEnd;
- (void)textSelectionInteractionWillBegin;
- (void)presentationControllerDidEndDismissing:(UIViewController *)arg1;
- (void)presentationControllerWillBeginDismissing:(UIViewController *)arg1;
- (void)presentationControllerDidEndPresenting:(UIViewController *)arg1;
- (void)presentationControllerWillBeginPresenting:(UIViewController *)arg1;
- (UIScrollView *)containingScrollView;
- (UIView *)customSnapshotView;
- (UIView *)mainViewForTouchDelivery;
- (_Bool)delaysSharingTouchesUntilAppeared;
- (_Bool)wantsToShareTouches;
- (void)willDeactivateHosting;
- (void)willActivateHosting;
@end

