//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAlert.h"

@interface SBNetworkReselectionAlert : SBAlert
{
}

+ (void)_handleNetworkReselectionNeeded:(_Bool)arg1 forSlot:(long long)arg2;
+ (void)_networkReselectionStateChanged:(id)arg1;
+ (void)test;
+ (void)registerForAlerts;

@end

