//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBNotificationManagementContentProvider.h"

@class NSString;
@protocol SBNotificationManagementSuggestionDelegate;

@interface SBNotificationManagementSuggestionContentProvider : SBNotificationManagementContentProvider
{
    _Bool _auxiliaryOptionsVisible;
    NSString *_optionsSummaryText;
    unsigned long long _numberOfOptionButtons;
    id <SBNotificationManagementSuggestionDelegate> _suggestionDelegate;
}

@property(nonatomic) __weak id <SBNotificationManagementSuggestionDelegate> suggestionDelegate; // @synthesize suggestionDelegate=_suggestionDelegate;
- (void)setAuxiliaryOptionsVisible:(_Bool)arg1;
- (_Bool)auxiliaryOptionsVisible;
@property(nonatomic) unsigned long long numberOfOptionButtons; // @synthesize numberOfOptionButtons=_numberOfOptionButtons;
@property(retain, nonatomic) NSString *optionsSummaryText; // @synthesize optionsSummaryText=_optionsSummaryText;
- (void).cxx_destruct;
- (void)logSuggestionResponse:(long long)arg1;
- (void)configureOptionButtons:(id)arg1;
- (id)initWithNotificationRequest:(id)arg1 bundleDisplayName:(id)arg2 managementDelegate:(id)arg3 suggestionDelegate:(id)arg4;

@end

