//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NCNotificationAlertDestination-Protocol.h"
#import "SBAssistantObserver-Protocol.h"
#import "SBStarkNotificationBannerSourceDelegate-Protocol.h"
#import "SBStarkScreenManagerObserver-Protocol.h"

@class DNDEventBehaviorResolutionService, NSString, SBAssistantController, SBStarkNotificationBannerSource;
@protocol NCNotificationAlertDestinationDelegate, NCNotificationDestinationDelegate;

@interface SBNotificationLegacyCarDestination : NSObject <SBStarkScreenManagerObserver, SBStarkNotificationBannerSourceDelegate, SBAssistantObserver, NCNotificationAlertDestination>
{
    id <NCNotificationAlertDestinationDelegate> _delegate;
    SBAssistantController *_assistantController;
    SBStarkNotificationBannerSource *_notificationBannerSource;
    DNDEventBehaviorResolutionService *_dndEventBehaviorResolutionService;
}

@property(retain, nonatomic) DNDEventBehaviorResolutionService *dndEventBehaviorResolutionService; // @synthesize dndEventBehaviorResolutionService=_dndEventBehaviorResolutionService;
@property(retain, nonatomic) SBStarkNotificationBannerSource *notificationBannerSource; // @synthesize notificationBannerSource=_notificationBannerSource;
@property(retain, nonatomic) SBAssistantController *assistantController; // @synthesize assistantController=_assistantController;
@property(nonatomic) __weak id <NCNotificationDestinationDelegate> delegate;
- (void).cxx_destruct;
- (void)_setNotificationBannerSourceForStarkScreenManager:(id)arg1;
- (void)assistant:(id)arg1 viewDidDisappear:(long long)arg2;
- (void)executeAction:(id)arg1 forNotificationRequest:(id)arg2;
- (void)starkScreenManagerDidChangeCurrentController:(id)arg1;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)modifyNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (_Bool)canReceiveNotificationRequest:(id)arg1;
@property(readonly, nonatomic) NSString *identifier;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

