//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBNotificationManagementSuggestionContentProvider.h"

@interface SBNotificationManagementPromotingSuggestionContentProvider : SBNotificationManagementSuggestionContentProvider
{
}

- (void)logSuggestionResponse:(long long)arg1;
- (void)handleOffAction:(id)arg1;
- (void)handleKeepAction:(id)arg1;
- (void)configureOptionButtons:(id)arg1;
- (id)initWithNotificationRequest:(id)arg1 bundleDisplayName:(id)arg2 managementDelegate:(id)arg3 suggestionDelegate:(id)arg4;

@end

