//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NCAuxiliaryOptionsProviding-Protocol.h"

@class NCNotificationRequest, NSString;
@protocol SBNotificationManagementDelegate;

@interface SBNotificationManagementContentProvider : NSObject <NCAuxiliaryOptionsProviding>
{
    NCNotificationRequest *_notificationRequest;
    id <SBNotificationManagementDelegate> _managementDelegate;
}

@property(nonatomic) __weak id <SBNotificationManagementDelegate> managementDelegate; // @synthesize managementDelegate=_managementDelegate;
@property(retain, nonatomic) NCNotificationRequest *notificationRequest; // @synthesize notificationRequest=_notificationRequest;
- (void).cxx_destruct;
- (void)handleManageAction:(id)arg1;
- (void)configureOptionButtons:(id)arg1;
- (id)initWithNotificationRequest:(id)arg1 managementDelegate:(id)arg2;

// Remaining properties
@property(nonatomic) _Bool auxiliaryOptionsVisible;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) unsigned long long numberOfOptionButtons;
@property(readonly, copy, nonatomic) NSString *optionsSummaryText;
@property(readonly, copy, nonatomic) NSString *optionsSummaryTitle;
@property(readonly) Class superclass;

@end

