//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBViewMorphAnimatorObserver-Protocol.h"

@class NSString, NSUUID, PGPictureInPictureViewController, SBPIPMorphAnimatorDataSource, SBViewMorphAnimator;

@interface SBPIPMorphAnimatorController : NSObject <SBViewMorphAnimatorObserver>
{
    NSUUID *_uuid;
    SBViewMorphAnimator *_viewMorphAnimator;
    SBPIPMorphAnimatorDataSource *_viewMorphAnimatorDataSource;
    PGPictureInPictureViewController *_pictureInPictureViewController;
    long long _startedSourceAnimations;
    long long _completedTargetAnimations;
}

@property(nonatomic) long long completedTargetAnimations; // @synthesize completedTargetAnimations=_completedTargetAnimations;
@property(nonatomic) long long startedSourceAnimations; // @synthesize startedSourceAnimations=_startedSourceAnimations;
@property(nonatomic) __weak PGPictureInPictureViewController *pictureInPictureViewController; // @synthesize pictureInPictureViewController=_pictureInPictureViewController;
@property(readonly, nonatomic) SBPIPMorphAnimatorDataSource *viewMorphAnimatorDataSource; // @synthesize viewMorphAnimatorDataSource=_viewMorphAnimatorDataSource;
@property(readonly, nonatomic) SBViewMorphAnimator *viewMorphAnimator; // @synthesize viewMorphAnimator=_viewMorphAnimator;
@property(readonly, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (void)animatorWasInterrupted:(id)arg1;
- (void)didEndTargetAnimations:(unsigned long long)arg1 finished:(_Bool)arg2 continueBlock:(CDUnknownBlockType)arg3;
- (void)didEndSourceAnimations:(unsigned long long)arg1 finished:(_Bool)arg2 continueBlock:(CDUnknownBlockType)arg3;
- (void)_terminate;
- (void)interrupt;
- (void)cancel;
- (int)targetProcessIdentifier;
- (id)init;
- (id)initWithTargetProcessIdentifier:(int)arg1 uuid:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

