//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface SBPieChartView : UIView
{
    NSArray *_slices;
    double _valueTotal;
    double _radius;
    struct CGPoint _center;
    double _defaultRotation;
}

- (void).cxx_destruct;
- (void)_drawSlice:(id)arg1 atValue:(double)arg2;
- (void)_rotateContext;
- (void)_updateMetrics;
- (void)drawRect:(struct CGRect)arg1;
- (void)setSlices:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

