//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SBHIDUILockAssertion;

@protocol SBProximitySensorControlling <NSObject>
@property(nonatomic) _Bool pocketTouchesExpected;
@property(nonatomic, getter=isProximityDetectionEnabled) _Bool proximityDetectionEnabled;
- (SBHIDUILockAssertion *)suspendProximityDetectionAndMultitouchForSource:(long long)arg1 reason:(NSString *)arg2;
- (SBHIDUILockAssertion *)suspendProximityDetectionForSource:(long long)arg1 reason:(NSString *)arg2;
- (void)resetProximityCalibration;
@end

