//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SBApplication;
@protocol SBProxyRemoteViewDelegate;

@interface SBProxyRemoteView : UIView
{
    id <SBProxyRemoteViewDelegate> _delegate;
    SBApplication *_app;
    NSString *_remoteViewIdentifier;
    _Bool _remoteViewOpaque;
    NSString *_hostRequester;
}

+ (Class)layerClass;
@property(nonatomic) _Bool remoteViewOpaque; // @synthesize remoteViewOpaque=_remoteViewOpaque;
@property(nonatomic) __weak id <SBProxyRemoteViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *remoteViewIdentifier; // @synthesize remoteViewIdentifier=_remoteViewIdentifier;
- (void).cxx_destruct;
- (void)disconnect;
- (void)noteConnectionLost;
- (void)_setIsConnected:(_Bool)arg1;
- (void)connectToContextID:(unsigned int)arg1 forIdentifier:(id)arg2 application:(id)arg3;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)init;

@end

