//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWorkspaceEntity.h"

@interface SBPreviousWorkspaceEntity : SBWorkspaceEntity
{
    long long _previousLayoutRole;
}

+ (id)entityWithPreviousLayoutRole:(long long)arg1;
@property(readonly, nonatomic) long long previousLayoutRole; // @synthesize previousLayoutRole=_previousLayoutRole;
- (_Bool)isPreviousWorkspaceEntity;
- (id)initWithIdentifier:(id)arg1 displayChangeSettings:(id)arg2;
- (id)initWithPreviousLayoutRole:(long long)arg1;

@end

