//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@class NSString;

@interface SBPrototypeControllerSettings : SBUISettings
{
    _Bool _preventLockover;
    _Bool _allowPrototypeSettings;
    NSString *_testRecipeClassName;
    double _windowAlpha;
}

@property _Bool allowPrototypeSettings; // @synthesize allowPrototypeSettings=_allowPrototypeSettings;
@property _Bool preventLockover; // @synthesize preventLockover=_preventLockover;
@property double windowAlpha; // @synthesize windowAlpha=_windowAlpha;
@property(retain) NSString *testRecipeClassName; // @synthesize testRecipeClassName=_testRecipeClassName;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

