//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBAWDMetricDelegate-Protocol.h"
#import "SBPressCollectorDelegate-Protocol.h"

@class NSString, NSUUID, SBPressCollector;
@protocol SBPressSequenceObserverDelegate;

@interface SBPressSequenceObserver : NSObject <SBPressCollectorDelegate, SBAWDMetricDelegate>
{
    NSUUID *_sosTriggerUUID;
    NSString *_pressName;
    SBPressCollector *_pressCollector;
    id <SBPressSequenceObserverDelegate> _delegate;
}

@property(nonatomic) __weak id <SBPressSequenceObserverDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SBPressCollector *pressCollector; // @synthesize pressCollector=_pressCollector;
@property(readonly, nonatomic) NSString *pressName; // @synthesize pressName=_pressName;
- (void).cxx_destruct;
- (void)_setPressCollector:(id)arg1;
- (void)_notePowerDownImminent;
- (void)metricDidPost:(id)arg1 data:(id)arg2;
- (void)pressCollector:(id)arg1 didCollectSequence:(id)arg2;
- (void)noteDidBeginSOSWithUUID:(id)arg1;
- (id)initWithPressName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

