//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBPressSequenceSettings;

@interface SBPressSequenceValidator : NSObject
{
    SBPressSequenceSettings *_settings;
}

@property(readonly, nonatomic) SBPressSequenceSettings *settings; // @synthesize settings=_settings;
- (void).cxx_destruct;
- (long long)_modeForDesiredIndex:(unsigned long long)arg1 isDownEvent:(_Bool)arg2;
- (struct _SBPressSequenceValidatorBounds)_pressUpBoundsForDesiredIndex:(unsigned long long)arg1 sequence:(id)arg2;
- (struct _SBPressSequenceValidatorBounds)_pressDownBoundsForDesiredIndex:(unsigned long long)arg1 sequence:(id)arg2;
- (double)timeUntilNextPressEventIsInValidInSequence:(id)arg1 lastPressEventInSequenceIsDown:(_Bool)arg2;
- (_Bool)pressEventIsValidInSequence:(id)arg1 endingDownEvent:(_Bool)arg2 duration:(double)arg3;
- (id)initWithSettings:(id)arg1;
- (id)init;

@end

