//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDisplayItem, SBRecentDisplayItemsController;

@protocol SBRecentDisplayItemsControllerDelegate <NSObject>

@optional
- (_Bool)recentDisplayItemsController:(SBRecentDisplayItemsController *)arg1 shouldAddItem:(SBDisplayItem *)arg2;
- (void)recentDisplayItemsController:(SBRecentDisplayItemsController *)arg1 didMoveItemToFront:(SBDisplayItem *)arg2;
- (void)recentDisplayItemsController:(SBRecentDisplayItemsController *)arg1 didAddItem:(SBDisplayItem *)arg2 andDropItem:(SBDisplayItem *)arg3;
- (void)recentDisplayItemsController:(SBRecentDisplayItemsController *)arg1 didAddItem:(SBDisplayItem *)arg2;
- (void)recentDisplayItemsController:(SBRecentDisplayItemsController *)arg1 didRemoveItem:(SBDisplayItem *)arg2;
- (void)recentDisplayItemsControllerDidUpdateDisplayItems:(SBRecentDisplayItemsController *)arg1;
@end

