//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;
@protocol SBReusableViewMapDelegate;

@interface SBReusableViewMap : NSObject
{
    NSMapTable *_recycledViewsByClass;
    _Bool _invalidated;
    id <SBReusableViewMapDelegate> _delegate;
}

@property(nonatomic) __weak id <SBReusableViewMapDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)invalidate;
- (void)purgeAllViews;
- (void)purgeViewsForClass:(Class)arg1;
- (_Bool)isViewRecycled:(id)arg1;
- (void)recycleView:(id)arg1;
- (id)newViewOfClass:(Class)arg1;
- (id)viewOfClass:(Class)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (id)init;

@end

