//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol SBRestartManagerWorkspaceDataSource <NSObject>
- (_Bool)isUILocked;
- (NSString *)activePrimaryApplicationBundleID;
- (void)terminateAllApplicationsForReason:(long long)arg1 description:(NSString *)arg2 completion:(void (^)(_Bool))arg3;
@end

