//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBRootFolderView;

@protocol SBRootFolderViewPageStateObserver
- (void)rootFolderView:(SBRootFolderView *)arg1 didEndTransitionFromState:(long long)arg2 toState:(long long)arg3 successfully:(_Bool)arg4;
- (void)rootFolderView:(SBRootFolderView *)arg1 willEndTransitionToState:(long long)arg2 successfully:(_Bool)arg3;
- (void)rootFolderView:(SBRootFolderView *)arg1 didContinueTransitionToState:(long long)arg2 progress:(double)arg3;
- (void)rootFolderView:(SBRootFolderView *)arg1 willBeginTransitionToState:(long long)arg2 animated:(_Bool)arg3 interactive:(_Bool)arg4;
@end

