//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MTAlarmManager;

@interface SBScheduledAlarmObserver : NSObject
{
    MTAlarmManager *_alarmManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_updateAlarmStatusBarItem;
- (void)_nextAlarmChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

