//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSSceneClientSettingsDiff, FBSSceneSettings, FBSSceneSettingsDiff, FBSSceneTransitionContext, FBScene, NSSet, SBSceneHandle;

@protocol SBSceneHandleObserver <NSObject>

@optional
- (void)sceneHandle:(SBSceneHandle *)arg1 didUpdatePairingStatusForExternalSceneIdentifiers:(NSSet *)arg2;
- (void)sceneHandle:(SBSceneHandle *)arg1 didUpdateClientSettingsWithDiff:(FBSSceneClientSettingsDiff *)arg2 transitionContext:(FBSSceneTransitionContext *)arg3;
- (void)sceneHandle:(SBSceneHandle *)arg1 didUpdateSettingsWithDiff:(FBSSceneSettingsDiff *)arg2 previousSettings:(FBSSceneSettings *)arg3;
- (void)sceneHandle:(SBSceneHandle *)arg1 didUpdateContentState:(long long)arg2;
- (void)sceneHandle:(SBSceneHandle *)arg1 didDestroyScene:(FBScene *)arg2;
- (void)sceneHandle:(SBSceneHandle *)arg1 didCreateScene:(FBScene *)arg2;
@end

