//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardUIServices/BSTransaction.h>

@class NSString;

@interface SBSceneLayoutSynchronizeTransitionTransaction : BSTransaction
{
    NSString *_debugName;
}

- (void).cxx_destruct;
- (id)_graphNodeDebugName;
- (_Bool)_canBeInterrupted;
- (void)synchronize;
- (id)initWithDebugName:(id)arg1;
- (id)init;

@end

