//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconZoomAnimationContaining-Protocol.h"

@class SBIcon, SBIconView, SBScaleIconZoomAnimator, UIView;

@protocol SBScaleIconZoomAnimationContaining <SBIconZoomAnimationContaining>
- (void)returnScalingView;
- (UIView *)borrowScalingView;

@optional
- (void)prepareForAnimation:(SBScaleIconZoomAnimator *)arg1 withTargetIcon:(SBIcon *)arg2;
- (void)setContentAlpha:(double)arg1;
- (UIView *)matchMoveSourceViewForIconView:(SBIconView *)arg1;
- (UIView *)targetIconContainerView;
@end

