//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBTouchTemplatePinchGestureRecognizer.h"

@interface SBScrunchSystemGestureRecognizer : SBTouchTemplatePinchGestureRecognizer
{
}

+ (id)defaultTemplates;
- (double)animationDistance;
- (id)logCategory;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

