//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSceneView, UIView;
@protocol SBScenePlaceholderContentContext, SBScenePlaceholderContentView, SBScenePlaceholderContentViewProviderDelegate;

@protocol SBScenePlaceholderContentViewProvider <NSObject>
@property(nonatomic) __weak id <SBScenePlaceholderContentViewProviderDelegate> delegate;
- (UIView<SBScenePlaceholderContentView> *)sceneView:(SBSceneView *)arg1 requestsPlaceholderContentViewWithContext:(id <SBScenePlaceholderContentContext>)arg2;
@end

