//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBApplicationSceneHandle, SBLayoutState, SBSceneManager;

@protocol SBSceneManagerObserver <NSObject>

@optional
- (void)sceneManager:(SBSceneManager *)arg1 didChangeFromLayoutState:(SBLayoutState *)arg2 toLayoutState:(SBLayoutState *)arg3;
- (void)sceneManagerDidInvalidate:(SBSceneManager *)arg1;
- (void)sceneManager:(SBSceneManager *)arg1 didRemoveExternalForegroundApplicationSceneHandle:(SBApplicationSceneHandle *)arg2;
- (void)sceneManager:(SBSceneManager *)arg1 didAddExternalForegroundApplicationSceneHandle:(SBApplicationSceneHandle *)arg2;
@end

