//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@interface SBSetupUpgradeAlertItem : SBAlertItem
{
    _Bool _goingToSetup;
}

- (_Bool)allowLockScreenDismissal;
- (void)performUnlockAction;
- (int)alertPriority;
- (_Bool)shouldShowInLockScreen;
- (_Bool)allowInSetup;
- (_Bool)unlocksScreen;
- (_Bool)allowAutoUnlock;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (id)initWithGoingToSetup:(_Bool)arg1;

@end

