//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDashBoardHostedAppViewController.h"

@protocol SBSecureAppViewControllerDelegate;

@interface SBSecureAppViewController : SBDashBoardHostedAppViewController
{
}

- (void)configureDisplayLayoutElement:(id)arg1;
- (_Bool)handleEvent:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <SBSecureAppViewControllerDelegate> delegate; // @dynamic delegate;

@end

