//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBSeparatorView : UIView
{
    UIView *_nubView;
    _Bool _nubHighlighted;
}

@property(nonatomic, getter=isNubHighlighted) _Bool nubHighlighted; // @synthesize nubHighlighted=_nubHighlighted;
- (void).cxx_destruct;
- (void)_updateNubViewFrame;
@property(readonly, nonatomic) struct CGRect nubRect;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

