//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBMainDisplayWorkspaceAppInteractionEventSourceObserving-Protocol.h"

@class NSString, SBFloatingDockBehaviorAssertion;

@interface SBSetupManager : NSObject <SBMainDisplayWorkspaceAppInteractionEventSourceObserving>
{
    _Bool _inSetupMode;
    _Bool _inSetupModeReadyToExit;
    SBFloatingDockBehaviorAssertion *_inSetupFloatingDockBehaviorAssertion;
}

+ (id)sharedInstance;
@property(nonatomic, getter=isInSetupModeReadyToExit) _Bool inSetupModeReadyToExit; // @synthesize inSetupModeReadyToExit=_inSetupModeReadyToExit;
- (void).cxx_destruct;
- (void)eventSource:(id)arg1 didBeginTransitionToMode:(long long)arg2 withLayoutState:(id)arg3 activatingElement:(id)arg4 triggeredBy:(long long)arg5;
- (void)_clearFloatingDockAssertion;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (void)postLaunchCompleteNotificationForSetup;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

