//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSearchGesture;

@protocol SBSearchGestureObserver <NSObject>
- (void)searchGesture:(SBSearchGesture *)arg1 changedPercentComplete:(double)arg2;

@optional
- (void)searchGesture:(SBSearchGesture *)arg1 resetAnimated:(_Bool)arg2;
- (void)searchGesture:(SBSearchGesture *)arg1 completedShowing:(_Bool)arg2;
- (void)searchGesture:(SBSearchGesture *)arg1 startedShowing:(_Bool)arg2;
@end

