//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSceneManager.h"

#import "SBLayoutStateTransitionSceneEntityFrameProvider-Protocol.h"

@class NSString;

@interface SBSecureMainDisplaySceneManager : SBSceneManager <SBLayoutStateTransitionSceneEntityFrameProvider>
{
}

+ (Class)_applicationSceneHandleClass;
- (struct CGRect)sceneEntityFrameForWorkspaceEntity:(id)arg1 inLayoutState:(id)arg2;
- (id)sceneIdentityForApplication:(id)arg1;
- (void)_setupLayoutStateTransitionCoordinator:(id)arg1;
- (id)window;
- (id)sceneLayoutViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

