//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBLockScreenActionProvider-Protocol.h"

@class NSString, SBLockScreenActionContext;

@interface SBSimpleLockScreenActionProvider : NSObject <SBLockScreenActionProvider>
{
    SBLockScreenActionContext *_lockScreenActionContext;
}

@property(retain, nonatomic) SBLockScreenActionContext *lockScreenActionContext; // @synthesize lockScreenActionContext=_lockScreenActionContext;
- (void).cxx_destruct;
- (void)invalidateLockScreenActionContext;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

