//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardServices/SBSLockScreenContentAction.h>

@class SBApplicationSceneEntity;

@interface SBSLockScreenContentAction (InProcess)
@property(retain, nonatomic) SBApplicationSceneEntity *applicationSceneEntity;
- (_Bool)isInProcessAction;
@end

