//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBDosidoAnimator.h"

@class UIView;

@interface SBSlideOverDosidoAnimator : SBDosidoAnimator
{
    UIView *_fromContainerView;
    UIView *_toContainerView;
    UIView *_fromDimmingView;
    UIView *_toDimmingView;
}

+ (double)defaultDuration;
@property(readonly, nonatomic) UIView *toDimmingView; // @synthesize toDimmingView=_toDimmingView;
@property(readonly, nonatomic) UIView *fromDimmingView; // @synthesize fromDimmingView=_fromDimmingView;
@property(readonly, nonatomic) UIView *toContainerView; // @synthesize toContainerView=_toContainerView;
@property(readonly, nonatomic) UIView *fromContainerView; // @synthesize fromContainerView=_fromContainerView;
- (void).cxx_destruct;
- (void)_rotateViewIfNecessary:(id)arg1 inverted:(_Bool)arg2;
- (void)_cleanupDosido;
- (void)_animateDosidoWithFactory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_prepareDosido;
- (void)setToView:(id)arg1;
- (void)setFromView:(id)arg1;
- (id)initWithParentView:(id)arg1 fromOrientation:(long long)arg2;

@end

