//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SBAppStatusBarSettingsAssertion, UITextView;

@interface SBSMSClass0AboutViewController : UIViewController
{
    UITextView *_aboutContentView;
    SBAppStatusBarSettingsAssertion *_statusBarSettingsAssertion;
}

- (void).cxx_destruct;
- (id)formattedAboutText;
- (void)doneButtonTapped:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

