//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBNotificationStaticContentProvider.h"

@class NSTimer;

@interface SBSnoozeAlarmNotificationStaticContentProvider : SBNotificationStaticContentProvider
{
    double _fireTime;
    NSTimer *_tickTimer;
}

@property(retain, nonatomic) NSTimer *tickTimer; // @synthesize tickTimer=_tickTimer;
@property(nonatomic) double fireTime; // @synthesize fireTime=_fireTime;
- (void).cxx_destruct;
- (void)_tickTimerFired:(id)arg1;
- (id)_formatDuration:(double)arg1;
- (id)secondaryText;
- (id)title;
- (void)invalidateTimer;
- (void)dealloc;
- (id)init;
- (id)initWithNotificationRequest:(id)arg1 viewController:(id)arg2;

@end

