//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSOSLockGestureObserver;

@protocol SBSOSLockGestureObserverDelegate <NSObject>
- (void)sosLockDidTriggerSOS:(SBSOSLockGestureObserver *)arg1 completion:(void (^)(_Bool))arg2;

@optional
- (void)sosLockTriggerDidBecomeInactive:(SBSOSLockGestureObserver *)arg1;
- (void)sosLockTriggerDidBecomeActive:(SBSOSLockGestureObserver *)arg1;
@end

