//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UISpringLoadedInteractionBehavior-Protocol.h"

@class NSString;
@protocol SBSpringLoadedInteractionBehaviorDelegate;

@interface SBSpringLoadedInteractionBehavior : NSObject <UISpringLoadedInteractionBehavior>
{
    id <SBSpringLoadedInteractionBehaviorDelegate> _delegate;
}

@property(nonatomic) __weak id <SBSpringLoadedInteractionBehaviorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)interactionDidFinish:(id)arg1;
- (_Bool)shouldAllowInteraction:(id)arg1 withContext:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

