//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBCarApplicationSceneEntity.h"

@class CPSTemplateConnectionManager;

@interface SBStarkMapsTemplateUIEntity : SBCarApplicationSceneEntity
{
    CPSTemplateConnectionManager *_templateConnectionManager;
}

@property(readonly, nonatomic) CPSTemplateConnectionManager *templateConnectionManager; // @synthesize templateConnectionManager=_templateConnectionManager;
- (void).cxx_destruct;
- (Class)viewControllerClass;
- (_Bool)isStarkMapsTemplateUIEntity;
- (id)initWithApplication:(id)arg1 screenController:(id)arg2;

@end

