//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBUIBannerItem.h>

@class NSArray, NSDate, NSHashTable, NSMutableSet, NSString;
@protocol SBStarkSessionConfiguring;

@interface SBStarkBannerItem : SBUIBannerItem
{
    id <SBStarkSessionConfiguring> _configuration;
    NSHashTable *_observers;
    NSMutableSet *_displayReasons;
}

@property(readonly, nonatomic) id <SBStarkSessionConfiguring> configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)_callOrFaceTimeStateChanged;
- (_Bool)_inCallOrFaceTime;
- (_Bool)isStarkBannerItem;
- (_Bool)matchesContext:(id)arg1;
- (void)reloadDisplayProperties;
@property(readonly, copy, nonatomic) NSArray *subActionLabels;
- (_Bool)shouldShowModalSubActions;
- (CDUnknownBlockType)ignoreAction;
@property(readonly, nonatomic) long long effectiveDefaultActionType;
@property(readonly, nonatomic) long long defaultActionType;
@property(readonly, nonatomic) NSDate *sourceDate;
@property(readonly, nonatomic) NSArray *iconImages;
@property(readonly, copy, nonatomic) NSString *message;
@property(readonly, copy, nonatomic) NSString *subTitle;
@property(readonly, copy, nonatomic) NSString *title;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

@end

