//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconListView.h"

@class UIView;

@interface SBStarkRootIconListView : SBIconListView
{
    struct UIEdgeInsets _insets;
    UIView *_lastFocusedView;
}

+ (unsigned long long)iconColumnsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)maxVisibleIconRowsInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconRowsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconColumnsForScreenWidth:(double)arg1;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
- (void).cxx_destruct;
- (long long)iconLocation;
- (double)sideIconInset;
- (double)bottomIconInset;
- (double)topIconInset;
- (Class)baseIconViewClass;

@end

