//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SBLeafIcon;

@protocol SBStarkStatusBarIconVisibilityDelegate <NSObject>
- (SBLeafIcon *)leafIconForIdentifier:(NSString *)arg1;
- (_Bool)iconIsDisplayingBadgeForLeafIdentifier:(NSString *)arg1;
- (_Bool)iconIsVisibleForLeafIdentifier:(NSString *)arg1;
@end

