//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUISettings.h"

@interface SBStatusBarStyleOverridesSettings : SBUISettings
{
    _Bool _exclusive;
    _Bool _showsWhenForeground;
    int _styleOverride;
}

+ (id)settingsControllerModule;
@property(nonatomic) _Bool showsWhenForeground; // @synthesize showsWhenForeground=_showsWhenForeground;
@property(nonatomic) _Bool exclusive; // @synthesize exclusive=_exclusive;
@property(nonatomic) int styleOverride; // @synthesize styleOverride=_styleOverride;
- (void)setDefaultValues;

@end

