//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBLayoutElementViewController.h"

@interface SBStarkNowPlayingLayoutElementViewController : SBLayoutElementViewController
{
}

- (id)_newDisplayLayoutElementForEntity:(id)arg1;
- (unsigned long long)supportedContentInterfaceOrientations;
- (void)configureWithWorkspaceEntity:(id)arg1 forLayoutElement:(id)arg2 layoutState:(id)arg3 referenceFrame:(struct CGRect)arg4;

@end

