//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconListPageControl.h"

@interface SBStarkIconListPageControl : SBIconListPageControl
{
    double _scale;
}

@property(nonatomic) double scale; // @synthesize scale=_scale;
- (double)_indicatorSpacing;
- (id)_iconListIndicatorImage:(_Bool)arg1;

@end

