//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkAlertToAppWorkspaceTransaction.h"

@class SBAlert, SBWorkspaceAlert;

@interface SBStarkAlertToImpersonatedAppWorkspaceTransaction : SBStarkAlertToAppWorkspaceTransaction
{
    SBAlert *_fromAlert;
    SBWorkspaceAlert *_toAlert;
}

- (void).cxx_destruct;
- (void)_activateAlert;
- (id)_effectiveTopEntity;
- (void)_alertDidDeactivate;
- (void)_beginAnimation;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

@end

