//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkAppToAppWorkspaceTransaction.h"

@interface SBStarkAppExitedWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction
{
}

- (id)_setupAnimationFrom:(id)arg1 to:(id)arg2;
- (void)_setupMilestonesFrom:(id)arg1 to:(id)arg2;
- (void)_begin;
- (id)initWithTransitionRequest:(id)arg1 exitedApplicationSceneEntity:(id)arg2;

@end

