//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSceneLayoutViewController.h"

@protocol SBStarkSessionConfiguring;

@interface SBStarkSceneLayoutViewController : SBSceneLayoutViewController
{
    id <SBStarkSessionConfiguring> _configuration;
}

- (void).cxx_destruct;
- (struct CGRect)_referenceFrameForApplicationSceneEntity:(id)arg1 inLayoutState:(id)arg2;
- (struct CGRect)referenceFrameForIdentifier:(id)arg1 inLayoutState:(id)arg2;
- (struct CGRect)referenceFrameForEntity:(id)arg1 inLayoutState:(id)arg2;
- (void)_addLayoutElementViewController:(id)arg1 forLayoutElement:(id)arg2 entity:(id)arg3;
- (id)_displayConfiguration;
- (id)initWithSceneManager:(id)arg1 configuration:(id)arg2;
- (id)initWithDisplayIdentity:(id)arg1;

@end

