//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBFolderController.h"

@interface SBStarkFolderController : SBFolderController
{
    unsigned long long _interactionAffordances;
    _Bool _supportsKnobEvents;
    _Bool _supportsTouchEvents;
}

- (void)_configureForInnerFolderController:(id)arg1;
@property(nonatomic) unsigned long long interactionAffordances;
- (id)_iconPageIndicatorImageSetCache;
- (Class)_contentViewClass;

@end

