//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkWorkspaceTransaction.h"

#import "SBMainScreenApplicationSceneTransactionObserver-Protocol.h"
#import "SBSceneLayoutWorkspaceTransactionDelegate-Protocol.h"

@class NSString, SBSceneLayoutWorkspaceTransaction, SBWorkspaceEntity;

@interface SBStarkToAppWorkspaceTransaction : SBStarkWorkspaceTransaction <SBSceneLayoutWorkspaceTransactionDelegate, SBMainScreenApplicationSceneTransactionObserver>
{
    _Bool _fromAssistant;
    SBSceneLayoutWorkspaceTransaction *_layoutTransaction;
    _Bool _mainScenesDidCommit;
    CDUnknownBlockType _transitionCompletion;
}

- (void).cxx_destruct;
- (void)transaction:(id)arg1 didEndLayoutTransitionWithContinuation:(CDUnknownBlockType)arg2;
- (void)transaction:(id)arg1 performTransitionWithCompletion:(CDUnknownBlockType)arg2;
- (void)transactionWillBeginLayoutTransition:(id)arg1;
- (id)createSceneEntityForHandle:(id)arg1;
- (void)mainScreenApplicationSceneDidCommit:(id)arg1;
- (void)mainScreenApplicationSceneWillCommit:(id)arg1;
- (void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)arg1;
- (void)mainScreenApplicationTransactionDidCommitSceneUpdatesForEntities:(id)arg1;
- (_Bool)sb_conformsToMainScreenApplicationSceneTransactionObserverProtocol;
- (void)_begin;
- (id)_effectiveTopEntity;
- (void)_performTransition;
- (void)_completeTransition;
- (void)_evaluateShouldPerformTransition;
@property(readonly, nonatomic) SBWorkspaceEntity *toEntity;
- (id)initWithTransitionRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

