//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWorkspaceTransitionRequest.h"

@class SBStarkScreenController;

@interface SBStarkWorkspaceTransitionRequest : SBWorkspaceTransitionRequest
{
    SBStarkScreenController *_screenController;
}

+ (id)requestWithScreenController:(id)arg1;
@property(retain, nonatomic) SBStarkScreenController *screenController; // @synthesize screenController=_screenController;
- (void).cxx_destruct;
- (void)finalize;
- (id)_initWithScreenController:(id)arg1;
- (id)_initWithWorkspace:(id)arg1 displayConfiguration:(id)arg2;

@end

