//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBStarkScreenController;

@protocol SBStarkScreenControllerObserver <NSObject>
- (void)starkScreenController:(SBStarkScreenController *)arg1 didChangeStateFromState:(long long)arg2 toState:(long long)arg3;
@end

