//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBStarkNotificationViewController;
@protocol SBUIBannerView;

@protocol SBStarkNotificationViewControllerDelegate <NSObject>
- (void)notificationViewController:(SBStarkNotificationViewController *)arg1 stateDidChangeFrom:(int)arg2;
- (void)notificationViewController:(SBStarkNotificationViewController *)arg1 willDisplayBannerView:(id <SBUIBannerView>)arg2;
@end

