//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAlertWindowViewController.h"

@interface SBStarkAlertWindowViewController : SBAlertWindowViewController
{
}

- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (void)noteAlertWindow:(id)arg1 didDisplayAlert:(id)arg2;

@end

