//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBStarkStatusBarRecordingStateProviding-Protocol.h"

@class AVSystemController, NSString, SBApplicationController;
@protocol SBStarkSessionConfiguring;

@interface SBStarkStatusBarRecordingStateManager : NSObject <SBStarkStatusBarRecordingStateProviding>
{
    id <SBStarkSessionConfiguring> _configuration;
    NSString *_activeBundleIdentifier;
    SBApplicationController *_applicationController;
    AVSystemController *_avSystemController;
}

- (void).cxx_destruct;
- (_Bool)shouldShowRecordingItem;
- (id)recordingApplication;
- (void)setActiveBundleIdentifier:(id)arg1;
- (id)initWithConfiguration:(id)arg1 applicationController:(id)arg2 avSystemController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

