//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBIconView.h"

@interface SBStarkIconView : SBIconView
{
    _Bool _alwaysAppearsFocused;
}

+ (_Bool)supportsDragInteraction;
+ (double)_labelHeight;
+ (struct CGSize)maxLabelSize;
+ (struct CGRect)_rectForLayoutMetric:(int)arg1;
+ (struct CGSize)defaultIconSize;
+ (struct UIEdgeInsets)minimumInterIconSpacing;
+ (struct UIEdgeInsets)iconImagePaddingInsets;
+ (_Bool)canShowLabelAccessoryView;
+ (int)_defaultIconFormat;
+ (Class)_interactionlessIconViewClass;
@property(nonatomic) _Bool alwaysAppearsFocused; // @synthesize alwaysAppearsFocused=_alwaysAppearsFocused;
- (struct CGRect)_frameForLabel;
- (void)prepareForReuse;
- (id)_labelImageParameters;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (_Bool)canBecomeFocused;

@end

