//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWindow.h"

@class SBStarkStatusBarViewController;
@protocol SBStarkSessionConfiguring;

@interface SBStarkStatusBarWindow : SBWindow
{
    id <SBStarkSessionConfiguring> _configuration;
}

- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)_reversesLinearFocusWrapping;
@property(retain, nonatomic) SBStarkStatusBarViewController *rootViewController;
- (id)initWithScreen:(id)arg1 layoutStrategy:(id)arg2 debugName:(id)arg3 configuration:(id)arg4;

@end

