//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBCarPlayApplicationSceneLayoutElementViewController.h"

#import "SBSceneHandleObserver-Protocol.h"

@class CPSOverlayViewController, CPSTemplateConnectionManager, NSString, UIView;

@interface SBStarkMapsTemplateUILayoutElementViewController : SBCarPlayApplicationSceneLayoutElementViewController <SBSceneHandleObserver>
{
    CPSOverlayViewController *_currentOverlayViewController;
    CPSTemplateConnectionManager *_templateConnectionManager;
    UIView *_currentHostView;
}

- (void).cxx_destruct;
- (void)sceneHandle:(id)arg1 didCreateScene:(id)arg2;
- (void)_tearDownHostView;
- (void)_setupHostView;
- (void)_setOverlayViewController:(id)arg1;
- (void)invalidate;
- (void)configureWithWorkspaceEntity:(id)arg1 forLayoutElement:(id)arg2 layoutState:(id)arg3 referenceFrame:(struct CGRect)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

