//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIStatusBar;

@interface SBStatusBarContainer : NSObject
{
    UIStatusBar *_statusBar;
    NSString *_reason;
}

@property(retain, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(nonatomic) __weak UIStatusBar *statusBar; // @synthesize statusBar=_statusBar;
- (void).cxx_destruct;
- (id)description;
- (void)dealloc;

@end

