//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkBannerSource.h"

#import "SBStarkNotificationBannerItemDelegate-Protocol.h"

@class NSString;
@protocol SBStarkNotificationBannerSourceDelegate;

@interface SBStarkNotificationBannerSource : SBStarkBannerSource <SBStarkNotificationBannerItemDelegate>
{
    id <SBStarkNotificationBannerSourceDelegate> _delegate;
}

@property(nonatomic) __weak id <SBStarkNotificationBannerSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)executeAction:(id)arg1 forNotificationRequest:(id)arg2;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)modifyNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

