//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkBannerItem.h"

@class NCNotificationRequest;
@protocol SBStarkNotificationBannerItemDelegate;

@interface SBStarkNotificationBannerItem : SBStarkBannerItem
{
    NCNotificationRequest *_request;
    id <SBStarkNotificationBannerItemDelegate> _delegate;
}

@property(nonatomic) __weak id <SBStarkNotificationBannerItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_supportsSubActions;
- (id)_allActions;
- (id)_clearAction;
- (id)_supplementaryActions;
- (id)appName;
- (id)_subTitle;
- (id)_title;
- (id)subActions;
- (id)subActionLabels;
- (_Bool)shouldShowModalSubActions;
- (CDUnknownBlockType)action;
- (long long)defaultActionType;
- (_Bool)isSticky;
- (id)sourceDate;
- (id)iconImages;
- (id)message;
- (id)subTitle;
- (id)title;
- (void)updateRequestToInstance:(id)arg1;
- (_Bool)matchesContext:(id)arg1;
- (id)initWithRequest:(id)arg1 configuration:(id)arg2;
- (id)initWithConfiguration:(id)arg1;

@end

