//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBStarkAppToAppWorkspaceTransaction.h"

@class SBAlert, SBAlertChangeTransaction;

@interface SBStarkImpersonatedAppToAppWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction
{
    SBAlertChangeTransaction *_deactivateAlertTransaction;
    SBAlert *_deactivatingAlert;
}

- (void).cxx_destruct;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)_deactivateAlertIfPossible;
- (void)_handleFailureToLaunch;
- (void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)arg1;
- (id)_newAnimationFromAppToLauncher;
- (id)_newAnimationFromAppToNowPlaying;
- (id)_newAnimationFromAppToApp;
- (_Bool)_canBeInterrupted;
- (_Bool)canInterruptForTransitionRequest:(id)arg1;
- (void)_didComplete;
- (void)_doCommit;
- (id)initWithTransitionRequest:(id)arg1;

@end

