//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SBSwitcherInsertionRemovalContext : NSObject
{
    _Bool _insertion;
    _Bool _shouldLayoutAsVisible;
    _Bool _initialVisibility;
    _Bool _finalVisibility;
    unsigned long long _direction;
    NSArray *_appLayoutsToIncludeForAnimation;
}

@property(retain, nonatomic) NSArray *appLayoutsToIncludeForAnimation; // @synthesize appLayoutsToIncludeForAnimation=_appLayoutsToIncludeForAnimation;
@property(nonatomic) _Bool finalVisibility; // @synthesize finalVisibility=_finalVisibility;
@property(nonatomic) _Bool initialVisibility; // @synthesize initialVisibility=_initialVisibility;
@property(nonatomic) _Bool shouldLayoutAsVisible; // @synthesize shouldLayoutAsVisible=_shouldLayoutAsVisible;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(nonatomic, getter=isInsertion) _Bool insertion; // @synthesize insertion=_insertion;
- (void).cxx_destruct;

@end

