//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSystemServiceServerDelegate-Protocol.h"

@class SBSUnlockOptions, SBSystemServiceServer;
@protocol FBSServiceFacilityClientHandle;

@protocol SBSystemServiceServerLockScreenDelegate <SBSystemServiceServerDelegate>
- (void)systemServiceServer:(SBSystemServiceServer *)arg1 requestPasscodeUnlockUIWithOptions:(SBSUnlockOptions *)arg2 forClient:(id <FBSServiceFacilityClientHandle>)arg3 withCompletion:(void (^)(_Bool))arg4;
@end

