//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBSystemServiceServerDelegate-Protocol.h"

@class SBSystemServiceServer;
@protocol FBSServiceFacilityClientHandle;

@protocol SBSystemServiceServerStateDumpDelegate <SBSystemServiceServerDelegate>
- (void)systemServiceServer:(SBSystemServiceServer *)arg1 client:(id <FBSServiceFacilityClientHandle>)arg2 disableRemoteStateDumpWithCompletion:(void (^)(_Bool, NSString *))arg3;
- (void)systemServiceServer:(SBSystemServiceServer *)arg1 client:(id <FBSServiceFacilityClientHandle>)arg2 enableRemoteStateDumpWithTimeout:(long long)arg3 completion:(void (^)(_Bool, NSString *))arg4;
- (void)systemServiceServer:(SBSystemServiceServer *)arg1 client:(id <FBSServiceFacilityClientHandle>)arg2 requestStateDump:(unsigned long long)arg3 withCompletion:(void (^)(_Bool, NSString *, NSString *))arg4;
@end

