//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBPolygon, SBTouchTemplate;

@interface SBTemplateAndMorph : NSObject
{
    SBPolygon *_morphedCandidate;
    SBTouchTemplate *_touchTemplate;
}

@property(readonly, nonatomic) SBTouchTemplate *touchTemplate; // @synthesize touchTemplate=_touchTemplate;
@property(readonly, nonatomic) SBPolygon *morphedCandidate; // @synthesize morphedCandidate=_morphedCandidate;
- (void).cxx_destruct;
- (id)initWithTemplate:(id)arg1 morph:(id)arg2;

@end

