//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol SBTouchPassThroughContainerViewDelegate;

@interface SBTouchPassThroughContainerView : UIView
{
    id <SBTouchPassThroughContainerViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SBTouchPassThroughContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

