//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBTouchTemplateGestureRecognizer.h"

@interface SBTouchTemplatePinchGestureRecognizer : SBTouchTemplateGestureRecognizer
{
}

- (double)_computeHandSizeCompensationGain:(double)arg1;
- (double)_computeNonlinearSpeedGain:(double)arg1;
- (double)incrementalGestureMotionForCandidate:(id)arg1 withTransformAnalyzerInfo:(id)arg2;
- (_Bool)hasSignificantMotionToBegin;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

