//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBTouchTemplateGestureRecognizer.h"

@interface SBTouchTemplatePanGestureRecognizer : SBTouchTemplateGestureRecognizer
{
    _Bool _recognizesHorizontalPanning;
    _Bool _recognizesVerticalPanning;
}

+ (id)defaultTemplates;
@property(nonatomic) _Bool recognizesVerticalPanning; // @synthesize recognizesVerticalPanning=_recognizesVerticalPanning;
@property(nonatomic) _Bool recognizesHorizontalPanning; // @synthesize recognizesHorizontalPanning=_recognizesHorizontalPanning;
- (_Bool)_directionallyAcceptMotion;
- (struct CGPoint)_convertPortraitPoint:(struct CGPoint)arg1 toOrientation:(long long)arg2;
- (double)incrementalGestureMotionForCandidate:(id)arg1 withTransformAnalyzerInfo:(id)arg2;
- (_Bool)hasSignificantMotionToBegin;
- (double)_arcSize;
- (double)_arcCenter;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

