//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SBUIBiometricResource;

@protocol SBUIBiometricResourceObserver <NSObject>

@optional
- (void)biometricResource:(id <SBUIBiometricResource>)arg1 matchingEnabledDidChange:(_Bool)arg2;
- (void)biometricResource:(id <SBUIBiometricResource>)arg1 matchingAllowedDidChange:(_Bool)arg2;
- (void)biometricResource:(id <SBUIBiometricResource>)arg1 observeEvent:(unsigned long long)arg2;
@end

