//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIStarkStartupAnimation.h"

@class UIStatusBar, UIView;

@interface SBUIStarkStartupToAppAnimation : SBUIStarkStartupAnimation
{
    UIView *_fromLockoutView;
    UIStatusBar *_fakeStatusBar;
    _Bool _finished;
}

@property(readonly, nonatomic) UIView *fromLockoutView; // @synthesize fromLockoutView=_fromLockoutView;
- (void).cxx_destruct;
- (id)animationSettings;
- (void)_finishedAnimation:(_Bool)arg1;
- (id)_zoomInFactory;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_application:(id)arg1 processStateDidChange:(id)arg2;
- (id)_progressDependencies;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)_createViewToAnimate;
- (id)initWithApplicationSceneEntity:(id)arg1 fromLockoutView:(id)arg2 starkScreenController:(id)arg3;
- (id)initFromLockoutView:(id)arg1 starkScreenController:(id)arg2;

@end

