//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SBUIProgressiveBlur <NSObject>
- (void)completeIncrementalTransitionSuccessfully:(_Bool)arg1;
- (void)setTransitionProgress:(double)arg1;
- (void)completeTransitionSuccessfully:(_Bool)arg1;
- (void)prepareForTransitionToBlurred:(_Bool)arg1;
@end

