//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIStarkStartupAnimation.h"

@class NSMutableArray, SBStarkLockOutView;

@interface SBUIStarkStartupToLockoutAnimation : SBUIStarkStartupAnimation
{
    NSMutableArray *_viewsToSlideUp;
    SBStarkLockOutView *_toLockoutView;
    unsigned long long _significantAnimationsRemaining;
}

- (void).cxx_destruct;
- (void)_noteSignificantAnimationFinished;
- (void)_slideUpViewsWithSlideFactory:(id)arg1 fadeFactory:(id)arg2 delayIncrement:(double)arg3;
- (void)_finishViewForSlideUp:(id)arg1;
- (id)animationSettings;
- (double)_animationDelay;
- (double)_animationDuration;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)initFromLockoutView:(id)arg1 toLockoutView:(id)arg2 starkScreenController:(id)arg3;

@end

