//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIWorkspaceAnimationController.h"

@class SBMainSwitcherViewController;

@interface SBUISwitcherAnimationController : SBUIWorkspaceAnimationController
{
    _Bool _interruptible;
    SBMainSwitcherViewController *_switcherViewController;
    CDUnknownBlockType _animationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType animationBlock; // @synthesize animationBlock=_animationBlock;
@property(nonatomic) __weak SBMainSwitcherViewController *switcherViewController; // @synthesize switcherViewController=_switcherViewController;
@property(nonatomic, getter=_isInterruptible, setter=_setInterruptible:) _Bool _interruptible; // @synthesize _interruptible;
- (void).cxx_destruct;
- (id)_layoutState;
- (id)_previousLayoutState;
- (void)_addSignpostsForAnimationEnd;
- (void)_addSignpostsForAnimationStart;
- (void)_updatePPTsForAnimationEnd;
- (void)_updatePPTsForAnimationStart;
- (void)_didComplete;
- (void)_startAnimation;
- (id)animationSettings;
- (_Bool)isInterruptible;
- (_Bool)isReasonableMomentToInterrupt;
- (id)initWithWorkspaceTransitionRequest:(id)arg1 switcherViewController:(id)arg2 animationBlock:(CDUnknownBlockType)arg3;

@end

