//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol SBUIFullscreenAnimationViewDelegate;

@interface SBUIFullscreenAnimationView : UIView
{
    id <SBUIFullscreenAnimationViewDelegate> _delegate;
    _Bool _animating;
}

@property(readonly, nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) __weak id <SBUIFullscreenAnimationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_notifyDelegateThatAnimationIsDone;
- (void)_notifyDelegateAnimationBeganWithDuration:(double)arg1 delay:(double)arg2;
- (void)_animationEnded;
- (void)_animationBegan;
- (void)endTransition;
- (void)beginTransition;
- (void)setToView:(id)arg1;
- (void)setFromView:(id)arg1;

@end

