//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;
@protocol SBUIPowerDownViewInterface;

@protocol SBUIPowerDownViewDelegate <NSObject>
- (void)powerDownViewWillAnimateOut:(UIView<SBUIPowerDownViewInterface> *)arg1;
- (void)powerDownViewWillAnimateIn:(UIView<SBUIPowerDownViewInterface> *)arg1;
- (void)powerDownViewAnimateOutCompleted:(UIView<SBUIPowerDownViewInterface> *)arg1;
- (void)powerDownViewRequestPowerDown:(UIView<SBUIPowerDownViewInterface> *)arg1;
- (void)powerDownViewRequestCancel:(UIView<SBUIPowerDownViewInterface> *)arg1;
@end

