//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIStarkScreenAnimationController.h"

@class SBAlert, UIView;

@interface SBUIStarkAnimationZoomDownApp : SBUIStarkScreenAnimationController
{
    SBAlert *_alertImpersonator;
    UIView *_viewToAnimate;
}

- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (id)animationSettings;
- (double)animationDelay;
- (double)animationStartTime;
- (double)animationDuration;
- (void)_prepareAnimation;
- (_Bool)prefersLayerHostSnapshot;
- (void)dealloc;
- (id)initWithDeactivatingApplicationSceneEntity:(id)arg1 withAlertImpersonator:(id)arg2 starkScreenController:(id)arg3;
- (id)initWithDeactivatingApplicationSceneEntity:(id)arg1 starkScreenController:(id)arg2;

@end

