//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAlertViewAdapter.h"

@interface SBUIFullscreenAlertViewAdapter : SBAlertViewAdapter
{
    _Bool _revealedContentBeneathForDismiss;
    _Bool _animatingOut;
}

- (void)setAlert:(id)arg1;
- (void)setShouldAnimateIn:(_Bool)arg1;
- (void)dismiss;
- (void)viewAnimatedOut;
- (_Bool)isAnimatingOut;
- (_Bool)shouldAnimateIconsIn;
- (void)alertDisplayWillBecomeVisible;
- (_Bool)isReadyToBeRemovedFromView;
- (id)alert;

@end

