//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIAnimationController.h"

@class _SBUIStarkZoomUpNowPlayingFromHomeAnimation;

@interface SBUIStarkZoomUpNowPlayingFromHomeAnimation : SBUIAnimationController
{
    _SBUIStarkZoomUpNowPlayingFromHomeAnimation *_animation;
}

- (void).cxx_destruct;
- (id)animationSettings;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)initWithToApplicationSceneEntity:(id)arg1 alertImpersonator:(id)arg2 starkScreenController:(id)arg3;

@end

