//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIRemoteAlertServiceInterface-Protocol.h"

@protocol SBUIRemoteAlertServiceInterface_Internal <SBUIRemoteAlertServiceInterface>
- (void)sb_resignFirstResponder;
- (void)sb_becomeFirstResponder;
@end

