//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UISettings.h>

@class NSHashTable;

@interface SBUISettings : _UISettings
{
    NSHashTable *_managedkeyObservers;
    NSHashTable *_managedKeyPathObservers;
}

- (void).cxx_destruct;
- (void)addKeyPathObserverIfPrototyping:(id)arg1;
- (void)addKeyObserverIfPrototyping:(id)arg1;
- (_Bool)_isPrototypingEnabled:(id)arg1;
- (void)removeKeyPathObserver:(id)arg1;
- (void)removeKeyObserver:(id)arg1;
- (void)_prototypingIsAllowedSettingChanged:(id)arg1;
- (void)dealloc;
- (void)setDefaultValues;

@end

