//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBUIAnimationController.h"

@class _SBUIStarkDosidoNowPlayingAnimation;

@interface SBUIStarkDosidoNowPlayingAnimation : SBUIAnimationController
{
    _SBUIStarkDosidoNowPlayingAnimation *_animation;
    _Bool _waitsForAppActivation;
}

- (void).cxx_destruct;
- (id)_viewToAnimateForApp:(id)arg1 animationIdentifier:(id)arg2;
- (id)animationSettings;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)initFromAlertImpersonator:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2;
- (id)initFromNowPlayingToAlertImpersonator:(id)arg1 starkScreenController:(id)arg2;
- (id)initFromApplicationSceneEntity:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2;
- (id)initFromNowPlayingToApplicationSceneEntity:(id)arg1 starkScreenController:(id)arg2;
- (id)initFromNowPlayingToNowPlayingWithStarkScreenController:(id)arg1;
- (void)_commonInitWithTransitionContextProvider:(id)arg1 starkScreenController:(id)arg2 waitForNowPlaying:(_Bool)arg3 initializationParametersBlock:(CDUnknownBlockType)arg4;

@end

