//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBUserNotificationCenter : NSObject
{
}

+ (void)_userNotificationDone:(id)arg1;
+ (void)startUserNotificationCenter;
+ (void)dispatchUserNotificationFromMachMessage:(CDStruct_a54b61c1 *)arg1 auditToken:(const CDStruct_6ad76789 *)arg2;

@end

