//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBViewControllerPercentCompletionReporting-Protocol.h"
#import "SBViewControllerReversibleAnimatedTransitioning-Protocol.h"

@protocol SBViewControllerContextTransitioning;

@protocol SBViewControllerInteractiveAnimatedTransitioning <SBViewControllerReversibleAnimatedTransitioning, SBViewControllerPercentCompletionReporting>
- (void)finishInteractiveTransition:(id <SBViewControllerContextTransitioning>)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)updateTransition:(id <SBViewControllerContextTransitioning>)arg1 withPercentComplete:(double)arg2;
@end

