//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBViewMorphAnimator;

@protocol SBViewMorphAnimatorDataSource <NSObject>
- (double)targetFinalCornerRadiusForAnimator:(SBViewMorphAnimator *)arg1;
- (struct CGRect)targetFinalFrameForAnimator:(SBViewMorphAnimator *)arg1;
- (struct CGRect)sourceContentFrameForAnimator:(SBViewMorphAnimator *)arg1;
@end

