//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBViewControllerPercentCompletionReporting-Protocol.h"
#import "SBViewControllerReversibleTransitioning-Protocol.h"
#import "SBViewControllerTransitionRestartedReporting-Protocol.h"
#import "UIViewControllerContextTransitioning-Protocol.h"

@protocol SBViewControllerContextTransitioning <UIViewControllerContextTransitioning, SBViewControllerReversibleTransitioning, SBViewControllerPercentCompletionReporting, SBViewControllerTransitionRestartedReporting>
- (_Bool)wasPreviousPhaseInteractive;
- (_Bool)initiallyInteractive;
- (void)restartTransition;
- (_Bool)supportsRestarting;
- (_Bool)supportsCancelling;
- (_Bool)isTransitioning;
@end

