//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class BSUIAnimationFactory;
@protocol SBViewControllerContextTransitioning;

@protocol SBViewControllerAnimatedTransitioning <UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <SBViewControllerContextTransitioning>)arg1;
- (double)transitionDuration:(id <SBViewControllerContextTransitioning>)arg1;

@optional
- (unsigned long long)transitionAnimationOptions:(id <SBViewControllerContextTransitioning>)arg1;
- (BSUIAnimationFactory *)transitionAnimationFactory:(id <SBViewControllerContextTransitioning>)arg1;
@end

