//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, SBApplication;

@interface SBVolumeHardwareButtonActions : NSObject
{
    SBApplication *_lastVolumeUpEventRecipient;
    SBApplication *_lastVolumeDownEventRecipient;
    _Bool _SBUIControllerWaitingForIncreaseUp;
    _Bool _SBUIControllerWaitingForDecreaseUp;
    _Bool _volumeIncreaseIsDown;
    _Bool _volumeDecreaseIsDown;
    NSHashTable *_volumePressBandits;
}

- (void).cxx_destruct;
- (_Bool)_handleVolumeButtonDownForIncrease:(_Bool)arg1;
- (_Bool)_handleVolumeButtonUpForIncrease:(_Bool)arg1;
- (_Bool)_handleVolumeDecreaseUp;
- (_Bool)_handleVolumeIncreaseUp;
- (_Bool)_sendVolumeButtonToSBUIControllerForIncrease:(_Bool)arg1 down:(_Bool)arg2;
- (void)_sendBanditsVolumeDecreased;
- (void)_sendBanditsVolumeIncreased;
- (void)removeVolumePressBandit:(id)arg1;
- (void)addVolumePressBandit:(id)arg1;
- (void)cancelVolumePress;
- (void)volumeDecreasePressUp;
- (void)volumeDecreasePressDown;
- (void)volumeIncreasePressUp;
- (void)volumeIncreasePressDown;

@end

