//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBAlertView.h"

#import "SUICFlamesViewDelegate-Protocol.h"
#import "SiriUISuggestionsViewDelegate-Protocol.h"
#import "VSRecognitionSessionDelegate-Protocol.h"
#import "VSSpeechSynthesizerDelegate-Protocol.h"

@class NSDictionary, NSString, SUICFlamesView, SiriUISuggestionsView, UILabel, UIView, VSRecognitionSession;

@interface SBVoiceControlAlertDisplay : SBAlertView <VSRecognitionSessionDelegate, VSSpeechSynthesizerDelegate, SUICFlamesViewDelegate, SiriUISuggestionsViewDelegate>
{
    VSRecognitionSession *_session;
    _Bool _wasRecognizing;
    _Bool _didConfigureRouting;
    UIView *_contentView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    SUICFlamesView *_flamesView;
    SiriUISuggestionsView *_suggestionsView;
    long long _keywordCount;
    long long _startingKeywordIndex;
    NSDictionary *_locStrings;
    _Bool _didDismiss;
    _Bool _awaitingButtonRelease;
    _Bool _isBecomingVisible;
    CDUnknownBlockType _postSoundBlock;
}

@property(copy, nonatomic) CDUnknownBlockType postSoundBlock; // @synthesize postSoundBlock=_postSoundBlock;
- (void).cxx_destruct;
- (float)audioLevelForFlamesView:(id)arg1;
- (id)nextSuggestionsForSuggestionsView:(id)arg1 maxSuggestions:(unsigned long long)arg2;
- (void)_keywordsChanged;
- (void)recognitionSession:(id)arg1 didFinishSpeakingFeedbackStringWithError:(id)arg2;
- (void)_speakText:(id)arg1;
- (void)_speakFeedbackText;
- (void)_performConfirmationAction;
- (void)_continueWithRecognitionAction;
- (id)recognitionSession:(id)arg1 openURL:(id)arg2;
- (_Bool)_openDialRequest:(id)arg1;
- (void)recognitionSession:(id)arg1 didCompleteActionWithError:(id)arg2;
- (void)_performNoMatchFound;
- (void)recognitionSessionDidBeginAction:(id)arg1;
- (void)_continueRecognitionAction;
- (_Bool)recognitionSessionWillBeginAction:(id)arg1;
- (void)_resetSession;
- (void)_startSession;
- (void)_configureRoutingIfNecessary;
- (void)_pickedRouteChanged:(id)arg1;
- (id)_desiredRouteDictionary;
- (void)handleHeadsetButtonUpFromActivation:(_Bool)arg1;
- (void)handleButtonUpCancel;
- (void)_dismissSlightlyLater;
- (void)dismiss;
- (void)_invalidateRouting;
- (void)alertWillBeDismissed;
- (void)alertDisplayWillBecomeVisible;
- (void)_setFeedbackVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setStatusText:(id)arg1;
- (void)setTitleText:(id)arg1;
- (id)_localizedStringForKey:(id)arg1;
- (_Bool)alphanumericKeyboard;
- (void)dealloc;
- (_Bool)_wasTriggeredByMenu;
- (double)_subtitleBaseline;
- (double)_titleBaseline;
- (id)initWithFrame:(struct CGRect)arg1 session:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

