//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBTransaction.h"

#import "SBSceneHandleObserver-Protocol.h"

@class NSString, SBSceneHandle;

@interface SBWaitForSceneContentAvailableTransaction : SBTransaction <SBSceneHandleObserver>
{
    SBSceneHandle *_sceneHandle;
    _Bool _isContentStateReady;
    _Bool _manualListener;
}

@property(readonly, copy, nonatomic) SBSceneHandle *sceneHandle; // @synthesize sceneHandle=_sceneHandle;
- (void).cxx_destruct;
- (void)_noteSceneContentReadinessDidChange:(_Bool)arg1;
- (void)sceneHandle:(id)arg1 didDestroyScene:(id)arg2;
- (void)sceneHandle:(id)arg1 didUpdateContentState:(long long)arg2;
- (_Bool)_canBeInterrupted;
- (void)_didComplete;
- (void)_begin;
- (void)noteSceneContentIsReady:(_Bool)arg1;
- (void)dealloc;
- (id)initWithSceneHandle:(id)arg1 manualListener:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

