//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSRecursiveLock, NSString, NWSystemPathMonitor;
@protocol OS_dispatch_source;

@interface SBWiFiManager : NSObject
{
    NSRecursiveLock *_lock;
    struct __CFRunLoop *_callbackRunLoop;
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    NSString *_deviceInterfaceName;
    _Bool _mainThread_devicePresent;
    struct __WiFiNetwork *_currentNetwork;
    struct __WiFiNetwork *_previousNetwork;
    _Bool _currentNetworkHasBeenSet;
    _Bool _currentNetworkIsIOSHotspot;
    _Bool _currentNetworkIsIOSHotspotHasBeenSet;
    _Bool _powered;
    _Bool _poweredHasBeenSet;
    int _mainThread_signalStrengthBars;
    int _mainThread_signalStrengthRSSI;
    _Bool _mainThread_signalStrengthHasBeenSet;
    NWSystemPathMonitor *_systemPathMonitor;
    NSObject<OS_dispatch_source> *_primaryInterfaceUpdateTimeoutSource;
    struct __WiFiNetwork *_primaryInterface;
    _Bool _primaryInterfaceHasBeenSet;
    _Bool _isPrimaryInterface;
    _Bool _isPrimaryInterfaceChanging;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_updateWiFiDevice;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_primaryInterfaceChanged:(_Bool)arg1;
- (id)_wifiInterface;
- (struct __CFRunLoop *)wifiRunLoopRef;
- (_Bool)isPrimaryInterface;
- (void)resetSettingsWithMode:(long long)arg1;
- (id)knownNetworks;
- (void)updateSignalStrength;
- (void)updateSignalStrengthFromRawRSSI:(int)arg1 andScaledRSSI:(float)arg2;
- (int)signalStrengthRSSI;
- (int)signalStrengthBars;
- (void)setWiFiEnabled:(_Bool)arg1;
- (_Bool)wiFiEnabled;
- (void)setPowered:(_Bool)arg1;
- (_Bool)isPowered;
- (id)currentNetworkName;
- (void)clearWiFiPickerPreferences;
- (_Bool)_cachedIsAssociated;
- (_Bool)isAssociatedToIOSHotspot;
- (_Bool)isAssociated;
- (void)_updateCurrentNetwork;
- (void)_linkDidChange;
- (void)_powerStateDidChange;
- (void)_updateWiFiState;
- (void)_runManagerCallbackThread;
- (void)_lock_spawnManagerCallbackThread;
- (struct __WiFiManagerClient *)_lock_manager;
- (void)_lock_setWiFiDevice:(struct __WiFiDeviceClient *)arg1;
- (void)updateDevicePresence;
- (_Bool)devicePresent;
- (_Bool)wifiSupported;
- (id)init;

@end

