//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBWindowLayoutStrategy-Protocol.h"

@class NSString;

@interface SBWindowLayoutStrategy : NSObject <SBWindowLayoutStrategy>
{
    _Bool _clip;
}

+ (id)noClipStrategy;
+ (id)clipStrategy;
+ (id)_strategyWithClipping:(_Bool)arg1;
- (_Bool)shouldClipForWindow:(id)arg1;
- (struct CGRect)frameOnScreen:(id)arg1 withInterfaceOrientation:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

