//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBTestRecipe-Protocol.h"

@class NSString;

@interface SBWidgetDebuggingTestRecipe : NSObject <SBTestRecipe>
{
}

+ (id)__systemService;
+ (id)title;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)_openNotificationCenter;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

