//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBWindowHideState : NSObject
{
    _Bool _hidden;
    double _desiredAlpha;
}

@property double desiredAlpha; // @synthesize desiredAlpha=_desiredAlpha;
@property(getter=isHidden) _Bool hidden; // @synthesize hidden=_hidden;
- (id)description;

@end

