//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;

@interface SBWorkItem : NSObject
{
    CDUnknownBlockType _workBlock;
    NSDate *_creationDate;
}

@property(readonly, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(readonly, copy, nonatomic) CDUnknownBlockType work; // @synthesize work=_workBlock;
- (void).cxx_destruct;
- (id)initWithWork:(CDUnknownBlockType)arg1;

@end

