//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBWorkspaceEntity.h"

@class SBAlert;

@interface SBWorkspaceAlert : SBWorkspaceEntity
{
    SBAlert *_alert;
}

+ (id)entityForAlert:(id)arg1;
@property(retain, nonatomic) SBAlert *alert; // @synthesize alert=_alert;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isAlertEntity;
- (CDUnknownBlockType)_generator;
- (_Bool)representsAlertOfClass:(Class)arg1;
@property(readonly, nonatomic) Class alertClass;
- (id)representedDisplay;
- (id)initWithAlert:(id)arg1;

@end

