//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SBCloseBoxView.h"

@interface SBXCloseBoxView : SBCloseBoxView
{
}

+ (struct UIEdgeInsets)backgroundInsets;
+ (id)defaultContentImage;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

