//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (SpringBoard)
- (double)sb_yPositionForLayoutAfterLabel:(id)arg1 baselineOffset:(double)arg2;
- (double)sb_yPositionForLabelWithContainerBounds:(struct CGRect)arg1 baselineOffset:(double)arg2 font:(id)arg3;
- (double)sb_yPositionForLabelWithContainerBounds:(struct CGRect)arg1 lineHeight:(double)arg2 baselineOffset:(double)arg3 font:(id)arg4;
@end

