//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BSAuditToken, FBSDisplayConfiguration, UISApplicationSupportDisplayEdgeInfo, UISDisplayContext;

@protocol UISApplicationSupportServiceDelegate <NSObject>

@optional
- (UISApplicationSupportDisplayEdgeInfo *)edgeInfoForClient:(BSAuditToken *)arg1 displayConfiguration:(FBSDisplayConfiguration *)arg2;
- (UISDisplayContext *)initialDisplayContextForClient:(BSAuditToken *)arg1;
- (FBSDisplayConfiguration *)initialDisplayConfigurationForClient:(BSAuditToken *)arg1;
- (void)requestPasscodeUnlockUIForClient:(BSAuditToken *)arg1 withCompletion:(void (^)(_Bool))arg2;
@end

