//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, UIImage, UITraitCollection;

@protocol UIStatusBarCarPlayDockDataProviding <NSObject>
- (_Bool)shouldDisplayBadgeForBundleIdentifier:(NSString *)arg1;
- (NSString *)callDuration;
- (UIImage *)dockImageForBundleIdentifier:(NSString *)arg1 format:(int)arg2 traitCollection:(UITraitCollection *)arg3;
- (NSString *)activeBundleIdentifier;
- (NSArray *)bundleIdentifiers;
@end

