//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIStatusBarStyleAnimationParameters, UIStatusBarStyleAttributes, UIStatusBar_Base;

@protocol UIStatusBarManager
- (_Bool)statusBar:(UIStatusBar_Base *)arg1 shouldRequestStyle:(long long)arg2 animationParameters:(UIStatusBarStyleAnimationParameters *)arg3 forced:(_Bool)arg4;
- (_Bool)statusBar:(UIStatusBar_Base *)arg1 shouldRequestStyleAttributes:(UIStatusBarStyleAttributes *)arg2 animationParameters:(UIStatusBarStyleAnimationParameters *)arg3 forced:(_Bool)arg4;
- (_Bool)statusBar:(UIStatusBar_Base *)arg1 shouldSetAlpha:(double)arg2;
@end

