//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIWindow.h>

@interface UIWindow (SelfHosting)
- (id)sb_hostWrapperForUseInOrientation:(long long)arg1 hostRequester:(id)arg2 enable:(_Bool)arg3 orderFront:(_Bool)arg4;
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2 enable:(_Bool)arg3 orderFront:(_Bool)arg4;
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2;
@end

