//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, UMUser;

@protocol UMCriticalUserSwitchStakeholder <NSObject>
- (void)readyToSwitchToUser:(UMUser *)arg1;
- (void)willSwitchToUser:(UMUser *)arg1;

@optional
- (void)userSwitchBlockingTasksDidUpdate:(NSDictionary *)arg1;
- (void)readyToSwitchToLoginSession:(UMUser *)arg1;
@end

