//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSURL, VSRecognitionSession;

@protocol VSRecognitionSessionDelegate <NSObject>

@optional
- (void)recognitionSession:(VSRecognitionSession *)arg1 didCompleteActionWithError:(NSError *)arg2;
- (void)recognitionSession:(VSRecognitionSession *)arg1 didFinishSpeakingFeedbackStringWithError:(NSError *)arg2;
- (NSError *)recognitionSession:(VSRecognitionSession *)arg1 openURL:(NSURL *)arg2;
- (void)recognitionSessionDidBeginAction:(VSRecognitionSession *)arg1;
- (_Bool)recognitionSessionWillBeginAction:(VSRecognitionSession *)arg1;
@end

