//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, UIImage, XBSnapshotDataProviderContext;
@protocol XBSnapshotDataProvider;

@protocol XBSnapshotDataProvider <NSObject>
@property(readonly, retain, nonatomic) XBSnapshotDataProviderContext *context;

@optional
- (void)invalidateImage;
- (_Bool)hasProtectedContent;
- (id <XBSnapshotDataProvider>)fallbackSnapshotDataProvider;
- (UIImage *)fetchImage;
- (NSData *)fetchImageData:(out struct CGAffineTransform *)arg1;
@end

